fix[loki-distributed]: add support for autoscaling ingester
grafana/helm-charts pull request #1047
Opened 2022-02-17 06:51 UTC by joshuasimon-taulia

I believe if you set replication_factor: 3, you can autoscale the ingester up and down. memory load seems to be evenly distributed to all of my replicas with a max of 6. mostly copied from https://github.com/grafana/helm-charts/pull/667

2022-02-18 09:08 UTC, Whyeasy commented
@joshuasimon-taulia Just to double check. You run your ingester with the deployment kind? Or with statefulset?

2022-02-18 17:45 UTC, joshuasimon-taulia commented
i'm currently running my ingester as a statefulset, but the included vpa logic will work with a deployment.

2022-03-31 20:46 UTC, trevorwhitney submitted a review, later dismissed
Can we remove the condition on # of replicas from the statefulset? This will match the what we have for the querier.

2022-03-31 20:46 UTC, trevorwhitney commented on charts/loki-distributed/templates/ingester/statefulset-ingester.yaml
> +{{- if not .Values.ingester.autoscaling.enabled }}
for consistency with the querier templates (which can also be run as either a deployment or a stateful set), I would advocate we not make replicas conditional on autoscaling here.

2022-06-15 17:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=1047) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=1047) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=1047) it.</sub>

2022-08-28 06:35 UTC, zanhsieh approved these changes

2022-08-31 12:36 UTC, zanhsieh requested changes

2022-08-31 12:36 UTC, zanhsieh commented on charts/loki-distributed/values.yaml
> +    targetMemoryUtilizationPercentage:
What is the default value here for memory?

2022-08-31 15:47 UTC, zanhsieh approved these changes

2022-08-31 15:49 UTC, merged