feat(loki): Add optional prometheusRule value/template
grafana/helm-charts pull request #1049
Opened 2022-02-17 08:28 UTC by eyenx

Adds an additional prometheusRule template for adding custom Rules which can be used by alertmanager to alert us.

It makes sure prometheusRules are only deployed if serviceMonitor is enabled

---

Signed-off-by: Toni Tauro <toni.tauro@adfinis.com>

2022-02-17 09:10 UTC, zanhsieh commented
@eyenx 
You need to bump the chart to the latest version, otherwise lint test won't pass.

2022-02-18 02:03 UTC, zanhsieh approved these changes

2022-02-18 02:05 UTC, zanhsieh requested changes

2022-02-18 02:05 UTC, zanhsieh commented on charts/loki/Chart.yaml
> +version: 2.10.0
2.10.1 ?

2022-02-18 05:34 UTC, eyenx commented on charts/loki/Chart.yaml
> +version: 2.10.0
@zanhsieh pls rereview

2022-02-19 02:39 UTC, zanhsieh approved these changes

2022-02-19 02:39 UTC, merged