Bump promtail to 2.4.2
grafana/helm-charts pull request #1094
Opened 2022-03-07 08:53 UTC by martinbeentjes

This PR bumps the Promtail version in the `loki-stack` chart to 2.4.2.

2022-03-07 10:27 UTC, zanhsieh commented
@martinbeentjes 
Please sign DCO. Thank you.

2022-03-07 14:09 UTC, martinbeentjes commented
@zanhsieh Signed DCO.

2022-03-07 14:35 UTC, feber commented
Apologies for jumping in, I have a question.
Should the `version` here point the application version, or chart version?
Because there are PRs that updates according to chart version. [[1]](https://github.com/grafana/helm-charts/pull/1054/files#diff-157a2ab75eb36d7f141f3e314b293bef4c0a8600b211287c42376320bdd40110R9) [[2]](https://github.com/grafana/helm-charts/pull/1045/files#diff-157a2ab75eb36d7f141f3e314b293bef4c0a8600b211287c42376320bdd40110R9)

2022-03-08 01:44 UTC, zanhsieh commented
@feber 
version = chart version
appVersion = the application itself version
@martinbeentjes 
I think you miss bumping chart version (version in Chart.yaml) to latest. Thank you.

2022-03-08 08:55 UTC, martinbeentjes commented
@zanhsieh fixed.

2022-03-08 11:33 UTC, zanhsieh approved these changes

2022-03-09 11:02 UTC, feber commented on charts/loki-stack/requirements.yaml
> +  version: "^2.4.2"
Perhaps the [error in pipeline](https://github.com/grafana/helm-charts/runs/5473495275?check_suite_focus=true#step:7:31) triggered by this?
Looking at the releases, there seems to be [no Chart with version 2.4.2](https://github.com/grafana/helm-charts/releases?expanded=true&page=3&q=promtail).

2022-03-09 11:02 UTC, feber commented on charts/loki-stack/requirements.yaml
> +  version: "^2.4.2"
Perhaps the [error in pipeline](https://github.com/grafana/helm-charts/runs/5473495275?check_suite_focus=true#step:7:31) triggered by this?
Looking at the releases, there seems to be [no Chart with version 2.4.2](https://github.com/grafana/helm-charts/releases?expanded=true&page=3&q=promtail).

2022-03-11 14:37 UTC, zanhsieh approved these changes

2022-03-11 14:56 UTC, martinbeentjes commented
@zanhsieh I saw that the version was wrong for Logstash and filebeat, should now be a valid chart version.

2022-03-14 08:09 UTC, zanhsieh approved these changes

2022-03-15 01:08 UTC, zanhsieh submitted a review, later dismissed

2022-03-16 13:34 UTC, lc-guy commented
Would be useful to have this merged -- current promtail dependency chart's default config breaks the log format (for parsing with loki datasource in grafana).

2022-03-17 01:09 UTC, zanhsieh commented
@martinbeentjes 
Please look into the lint-test log and fix the bug. Thank you.

2022-03-23 20:55 UTC, alteredtech commented
I figured out where the bug is but I am not sure how to implement a fix. Between promtail chart version 2.2.0 and 3.11.0, the config section was changed/added. In this section, config.lokiAddress was added. This address is put into config.file further down. In chart version 3.11.0, promtail is looking for loki-gateway as a host when it should be looking for I think loki.fullname:3100.
Basically it needs the name of the loki pod with port 3100. Unless there is a better way of doing it, when I changed my values file with lokiAddress to the name of the loki pod and port, it worked.

2022-03-23 21:53 UTC, feber commented
Thanks for digging into this @alteredtech.
Based on your finding, my local test passed by passing the release name:
```yml
promtail:
  enabled: true
  config:
    lokiAddress: http://{{ .Release.Name }}:3100/loki/api/v1/push
```

But I am not sure whether this is the correct/recommended/acceptable way to do it or not.

2022-03-24 06:31 UTC, martinbeentjes commented
Thanks all for helping out. I've been a bit too busy with my work to get some time to attempt a fix here. I've applied the snippet provided by @feber.

2022-03-25 15:02 UTC, zanhsieh approved these changes

2022-03-25 21:10 UTC, martinbeentjes commented
@zanhsieh is there anything I need to do for those two workflows to run? I expected your approval would be enough. Hopefully I can help out getting those to run. Thanks in advance!

2022-03-26 08:05 UTC, zanhsieh commented
@martinbeentjes 
It seems one more reviewer needs to approve. The "Merge pull request" button is gray-out in my side (can't click).

2022-03-30 09:59 UTC, stephaneetje commented
On the page of grafana's fluent-bit helm chart it sais it is depecrated. so we can't use fluentbit with loki-stack chart anymore ??

2022-03-30 10:18 UTC, martinbeentjes commented
@stephaneetje Good one, might be that we also need to change `charts/loki-stack/requirements.yaml` then.

```diff
 - name: "fluent-bit"
    condition: fluent-bit.enabled
-   repository: "https://grafana.github.io/helm-charts"
-   version: "^2.3.0"
+   repository: "https://fluent.github.io/helm-charts"
+   version: "^0.19.22"
```

2022-03-30 10:23 UTC, zdevi commented
The values.yaml must also be changed. There are diferences beetwen grafanas fluentbit and the official one

2022-03-30 10:24 UTC, martinbeentjes commented
Might be useful to create a separate PR to change this. First bump every version we are using right now. Then we remove the deprecated chart that is used.

2022-03-30 10:33 UTC, martinbeentjes commented
I have created #1140 for this change.

2022-04-03 06:59 UTC, martinbeentjes commented
@feber Could you do a review again, that would help out I think with getting the required approvals. Thanks in advance!

2022-04-03 15:30 UTC, feber approved these changes

2022-04-09 00:38 UTC, zanhsieh requested changes

2022-04-09 00:38 UTC, zanhsieh commented on charts/loki-stack/Chart.yaml
>  version: 2.6.2
need to bump to 2.6.3.

2022-04-14 11:18 UTC, gcaracuel commented on charts/loki-stack/Chart.yaml
> +version: 2.6.3
```suggestion
version: 2.6.4
```

Needs a version bump

2022-04-14 12:07 UTC, martinbeentjes commented on charts/loki-stack/Chart.yaml
> +version: 2.6.3
@gcaracuel done

2022-04-15 19:50 UTC, zanhsieh approved these changes

2022-04-15 19:59 UTC, merged

2022-04-22 03:35 UTC, danports commented
This PR introduces a breaking change (included in the `promtail` subchart upgrade) but only increments the `loki-stack` chart's patch version. Can we consider pulling version 2.6.4 and replacing it with a 3.0.0? See discussion in #1256.