[loki-simple-scalable] bump loki simple scalable version
grafana/helm-charts pull request #1151
Opened 2022-03-30 17:52 UTC by trevorwhitney

bump loki simple scalable version to fix [CI](https://github.com/grafana/helm-charts/runs/5746878892?check_suite_focus=true)

2022-03-31 01:12 UTC, zanhsieh requested changes

2022-03-31 01:12 UTC, zanhsieh commented on charts/loki-simple-scalable/Chart.yaml
> +version: 0.3.1
Should rebase to 0.3.2.

2022-03-31 01:12 UTC, zanhsieh commented on charts/loki-simple-scalable/README.md
> +![Version: 0.3.1](https://img.shields.io/badge/Version-0.3.1-informational?style=flat-square) ![Type: application](https://img.shields.io/badge/Type-application-informational?style=flat-square) ![App
Same as above.

2022-04-01 18:07 UTC, slim-bean approved these changes
LGTM

2022-04-01 19:24 UTC, merged