mimir: add standard prometheus pod annotations
grafana/helm-charts pull request #1181
Opened 2022-04-05 20:00 UTC by jmcarp

By convention, prometheus scrape configs often use the
`prometheus.io/scrape` and `prometheus.io/port` pod annotations to
configure kubernetes pod scrape targets. Similar to prometheus pod
annotations for other charts in this repo, this patch adds these
annotations to the relevant pods in the mimir chart.

Based on https://github.com/cortexproject/cortex-helm-chart/pull/288.

Signed-off-by: Josh Carp <jm.carp@gmail.com>

2022-04-06 06:49 UTC, krajorama requested changes
Hi, thank you for the contribution. I'd kindly ask you to create a template called "mimir.podAnnotations" in _helpers.tpl and have common annotations and these there. And then include the new template in the Deployment/StatefulSet definitions Or you can leave it to me and I'll open an issue. The reason being that values.yaml is meant for user settings and if the user sets podAnnotations themselves, they can easily overwrite these
annotations by accident.

2022-04-07 03:32 UTC, jmcarp commented
Updated. Is this roughly what you had in mind?

2022-04-07 10:59 UTC, krajorama commented
Yes, exactly, I just need to double check if this interferes with the "ServiceMonitor" setup I have going (and have a PR on), might have to add an "if"

2022-04-07 12:05 UTC, krajorama approved these changes
LGTM, please bump the version (0.1.5 at the moment) and run helm-docs (1.4.0) to update the readme, or just follow what the CI says. Let me know if you have trouble.

2022-04-21 12:44 UTC, ryan-dyer-sp commented
Shouldnt these be hidden behind a values variable?  This is just adding them to all pods and not all users need or want these annotations.  kube-prometheus-stack deprecated the use of these annotations in favor of servicemonitors a while back.

2022-04-25 16:11 UTC, jmcarp commented
@krajorama any preference on this? I'm happy to resolve conflicts or refactor a bit.

2022-04-28 07:50 UTC, krajorama commented
Since it's deprecated by prom, I wouldn't add it with it's own named value. Seems like another use case for #1284 on the other hand. @jmcarp so something like `global.podAnnotations` would be acceptable? Note that right now these wouldn't apply to subcharts (memcached and minio). Although it came up in another issue to change to memcached managed by our chart directly (#1315).

2022-06-15 17:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=1181) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=1181) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=1181) it.</sub>

2022-07-11 05:04 UTC, zanhsieh commented
Mimir-distrubuted repo moved. See:
https://github.com/grafana/helm-charts/blob/main/charts/mimir-distributed/README.md
Close this PR.

2022-07-11 05:04 UTC, closed without merging