Add loki-canary chart
grafana/helm-charts pull request #122
Opened 2020-12-09 22:16 UTC by unguiculus

2020-12-09 23:54 UTC, zanhsieh submitted a review, later dismissed

2020-12-10 20:50 UTC, torstenwalter requested changes

2020-12-10 20:50 UTC, torstenwalter commented on .github/CODEOWNERS
> +/charts/loki-canary @unguiculus
```suggestion
/charts/loki-canary @unguiculus
```

2020-12-10 20:50 UTC, torstenwalter commented on charts/loki-canary/README.md
> +helm repo add loki https://unguiculus.github.io/loki-helm-chart
```suggestion
helm repo add grafana https://grafana.github.io/helm-charts
```

2020-12-10 20:50 UTC, torstenwalter commented on charts/loki-canary/Chart.yaml
> +home: https://github.com/unguiculus/loki-helm-chart
```suggestion
home: https://github.com/grafana/helm-charts
```

2020-12-10 20:50 UTC, torstenwalter commented on charts/loki-canary/README.md.gotmpl
> +helm repo add loki https://unguiculus.github.io/loki-helm-chart
```suggestion
helm repo add grafana https://grafana.github.io/helm-charts
```

2020-12-10 21:09 UTC, torstenwalter approved these changes
lgtm

2020-12-10 21:09 UTC, merged