[grafana] Add affinity/node selector / tolerations docs for renderer
grafana/helm-charts pull request #1265
Opened 2022-04-20 11:33 UTC by thobianchi

Adds affinity/nodeselector/tolerations in README and in values ( empty ) for image renderer.  
The deployment already support this options.

2022-04-20 23:08 UTC, zanhsieh commented
@thobianchi 
Could you bump the chart version to latest in Chart.yaml? Thank you.

2022-04-20 23:08 UTC, zanhsieh commented
@thobianchi 
Could you bump the chart version to latest in Chart.yaml? Thank you.

2022-04-21 07:10 UTC, thobianchi commented
done

2022-04-21 07:51 UTC, zanhsieh approved these changes

2022-04-21 08:38 UTC, zanhsieh requested changes

2022-04-21 08:38 UTC, zanhsieh commented on charts/grafana/Chart.yaml
> +version: 6.26.4
6.26.5 now

2022-04-21 08:46 UTC, thobianchi commented on charts/grafana/Chart.yaml
> +version: 6.26.4
ok done

2022-04-21 10:42 UTC, zanhsieh approved these changes

2022-04-21 10:42 UTC, merged