[mimir-distributed] add named port memberlist to pod container
grafana/helm-charts pull request #1311
Opened 2022-04-27 10:37 UTC by ortuman

Signed-off-by: Miguel Ángel Ortuño <ortuman@gmail.com>

Add memberlist container named port to all components that depend on it.

2022-04-27 11:05 UTC, krajorama requested changes
Need to add the new named template to templates/_helpers.tpl.
If we chose to hardcode the number, we should add a validation against changing via mimir.config. Otherwise should have a default hardcoded value and try to grab the bind port via mimir.calculatedConfig (see other examples). I think we can go with the second option as it's not referenced anywhere in mimir.config, so no infinite loop....

2022-04-27 11:05 UTC, krajorama commented on charts/mimir-distributed/templates/alertmanager/alertmanager-dep.yaml
> +            - name: memberlist
alertmanager has a statefulset deployment option also!

2022-04-27 11:18 UTC, ortuman commented on charts/mimir-distributed/templates/alertmanager/alertmanager-dep.yaml
> +            - name: memberlist
done @ b9d9200db8a18a37fc6340fa95a512b0371cd9db

2022-04-28 07:24 UTC, krajorama approved these changes
LGTM

2022-04-28 07:30 UTC, merged