loki-distributed: added support for PSP
grafana/helm-charts pull request #134
Opened 2020-12-15 13:54 UTC by piontec

Loki-distributed is missing PSP (which is present in non-distributed loki).

2021-01-08 08:18 UTC, unguiculus requested changes
Thanks. I made a few comments.

2021-01-08 08:18 UTC, unguiculus commented on charts/loki-distributed/templates/role.yaml
> +  resourceNames:  [{{ include "loki.fullname" . }}]
Indent lists and use block style for lists.

2021-01-08 08:18 UTC, unguiculus commented on charts/loki-distributed/templates/rolebinding.yaml
> +  name: {{ include "loki.serviceAccountName" . }}
```suggestion
  - kind: ServiceAccount
    name: {{ include "loki.serviceAccountName" . }}
```

2021-01-08 08:18 UTC, unguiculus commented on charts/loki-distributed/values.yaml
> +  pspEnabled: True
```suggestion
  pspEnabled: true
```

2021-01-08 08:18 UTC, unguiculus commented on charts/loki-distributed/values.yaml
> +  # -- should PodSecurityPolicy be used
```suggestion
  # -- If enabled, a PodSecurityPolicy is created
```

2021-01-08 08:18 UTC, unguiculus commented on charts/loki-distributed/templates/podsecuritypolicy.yaml
> +      max: 65535
```suggestion
      - min: 1
        max: 65535
```

2021-01-08 08:18 UTC, unguiculus commented on charts/loki-distributed/templates/podsecuritypolicy.yaml
> +      max: 65535
```suggestion
      - min: 1
        max: 65535
```

2021-01-18 11:41 UTC, piontec commented
Hey!
Sorry for the long break, I'll try to clean it up

2021-01-25 16:55 UTC, unguiculus requested changes
I have a few more remarks.

2021-01-25 16:55 UTC, unguiculus commented on charts/loki-distributed/Chart.yaml
> +version: 0.22.3
```suggestion
version: 0.23.0
```

2021-01-25 16:55 UTC, unguiculus commented on charts/loki-distributed/templates/podsecuritypolicy.yaml
> +{{ if .Values.rbac.pspEnabled }}
```suggestion
{{- if .Values.rbac.pspEnabled }}
```

2021-01-25 16:55 UTC, unguiculus commented on charts/loki-distributed/templates/role.yaml
> +  - {{ include "loki.fullname" . }}
Lists should be indented. API group should be `policy`.
```suggestion
  - apiGroups:      
      - policy
    resources:      
      - podsecuritypolicies
    verbs:          
      - use
    resourceNames:  
      - {{ include "loki.fullname" . }}
```

2021-01-25 16:55 UTC, unguiculus commented on charts/loki-distributed/templates/rolebinding.yaml
> +{{ if .Values.rbac.pspEnabled }}
```suggestion
{{- if .Values.rbac.pspEnabled }}
```

2021-01-25 16:55 UTC, unguiculus commented on charts/loki-distributed/templates/role.yaml
> +{{ if .Values.rbac.pspEnabled }}
```suggestion
{{- if .Values.rbac.pspEnabled }}
```

2021-02-02 09:12 UTC, piontec commented
Ping @unguiculus , can you please have a look again?

2021-02-03 13:24 UTC, unguiculus requested changes

2021-02-03 13:24 UTC, unguiculus commented on charts/loki-distributed/values.yaml
> +  pspEnabled: true
Default should be false.

2021-02-03 13:24 UTC, unguiculus commented on charts/loki-distributed/Chart.yaml
> +version: 0.24.1
Bump minor version.

2021-02-05 13:31 UTC, unguiculus approved these changes

2021-02-05 13:32 UTC, merged