feat: add initContainers
grafana/helm-charts pull request #1340
Opened 2022-05-04 10:20 UTC by Grounz

Hi,
I submit this pr beacause when we want deploy loki simple-scalable helm charts we use boltdb-shipper.

When read and write loki pod start they have a var/loki/boltdb-shipper-active: permission denied errir and we cannot fix that without use an initContainer which do chown 10001:10001 /var/loki.

Loki-simple-scalable helm chart not containers initContainers in statefulset templates for read and write pods.

So i have add the possibility to add initContainers for read and for write pods.

in values.yaml:

```
write:
...
  initContainers: []
read:
...
  initContainers: []
```

Signed-off-by: lenglet-k <lenglet-k@mgdis.fr>

2022-06-18 04:15 UTC, zanhsieh commented
@Grounz 
Please bump the Chart.yaml to latest and sign license/cla. Thank you.

2022-06-28 22:30 UTC, trevorwhitney requested changes
Would prefer a `with` block so key is excluded rather than included with empty array. Also, please sign CLA.

2022-06-28 22:30 UTC, trevorwhitney commented on charts/loki-simple-scalable/templates/read/statefulset-read.yaml
> +      initContainers:
WDYT of wrapping this in a `with` block so the key is only included when init containers are provided?

2022-08-10 03:15 UTC, zanhsieh commented
@trevorwhitney @joe-elliott 
Documentation CI seems having some problem.

2022-09-04 12:11 UTC, zanhsieh commented
@Grounz 
Since loki and loki-simple-scalable moved to https://github.com/grafana/loki/tree/main/production/helm/loki . Please PR over there.

2022-09-04 12:11 UTC, closed without merging