[grafana] supported the case when only plugins are provisioned
grafana/helm-charts pull request #1432
Opened 2022-05-31 19:27 UTC by vlad-diachenko

**Issue:**
If neither provisioning of dashboards nor provisioning of datasources is enabled, but we need to provision only a plugin, we were not able to do it because the permissions to read configMaps and secrets were granted only if datasources or dashboards provisioning is enabled. 
Previously, if we deploy Grafana with only plugin provisioning enabled, the sidecar started reporting the errors that it does have access to query configMaps and secrets.

**Fix:**
added permissions to clusterRole and role to access "configmaps" and "secrets" if any resource(plugins or datasources or dashboards) provisioning is enabled. 

Signed-off-by: Vladyslav Diachenko <vlad.diachenko@grafana.com>

2022-06-03 14:39 UTC, zanhsieh requested changes

2022-06-03 14:39 UTC, zanhsieh commented on charts/grafana/Chart.yaml
> +version: 6.29.6
now 6.29.7

2022-06-10 07:37 UTC, vlad-diachenko commented on charts/grafana/Chart.yaml
> +version: 6.29.6
done

2022-06-11 02:20 UTC, zanhsieh approved these changes

2022-06-11 02:22 UTC, merged