[grafana] - HA Alerting: Allow StatefulSet to be used instead of Deployment
grafana/helm-charts pull request #1499
Opened 2022-06-15 12:20 UTC by jdziat

For HA Alerting:
Would like the ability to use a StatefulSet instead of a deployment. That way I can dynamically populate the ha-peers using predetermined host names.

Example:
```
ha_peers=grafana-0:9094,grafana-1:9094,grafana-2:9094
```

2022-06-21 23:46 UTC, zanhsieh commented
@jdziat 
This PR needs a version bump in Chart.yaml. Thank you in advance.

2022-06-22 00:08 UTC, jdziat commented
@zanhsieh bumped

2022-06-22 03:55 UTC, zanhsieh commented
@jdziat 
Please fix the CI error:
```
==> Linting charts/grafana
Error:  templates/: parse error at (grafana/templates/statefulset.yaml:1): unclosed left paren
```

2022-06-22 03:59 UTC, zanhsieh requested changes

2022-06-22 03:59 UTC, zanhsieh commented on charts/grafana/templates/statefulset.yaml
> +{{- if (or (.Values.useStatefulSet) (and .Values.persistence.enabled (not .Values.persistence.existingClaim) (eq .Values.persistence.type "statefulset"))}}
```
{{- if (or (.Values.useStatefulSet) (and .Values.persistence.enabled (not .Values.persistence.existingClaim) (eq .Values.persistence.type "statefulset")))}}
```

2022-06-22 04:06 UTC, zanhsieh approved these changes

2022-06-22 04:06 UTC, merged