[WIP]tempo: add microservice and single mode
grafana/helm-charts pull request #166
Opened 2021-01-07 11:12 UTC by swartz-k

Hey，all，Based [tempo chart](https://github.com/grafana/tempo/tree/master/operations/helm)，I have done littler worker to change tempo install more easily. 
Microservice mode still need some change and fully test, It will cost about 3 hours.

Signed-off-by: swartz-k <9215868@gmail.com>

2021-02-11 20:02 UTC, joe-elliott commented
I have run this locally and it works.  Is there anything keeping this from being merged?

2021-02-15 19:28 UTC, stevehipwell commented
Is there a timeframe for this?

2021-02-15 20:28 UTC, afoninsky approved these changes

2021-02-16 13:28 UTC, joe-elliott requested changes
one change requested and then i'll merge.

2021-02-16 13:28 UTC, joe-elliott commented on charts/tempo/values.yaml
> +  tag: latest
please change this to 0.5.0 and then I'll merge.  we should pin versions.

2021-02-17 17:04 UTC, joe-elliott approved these changes

2021-02-17 17:05 UTC, merged