grafana: add sidecar configmap label value select
grafana/helm-charts pull request #170
Opened 2021-01-08 15:07 UTC by ryanprobus

* Allows specification of the LABEL_VALUE environment variable on the
  kiwigrid/k8s-sidecar as labelValue helm value for the datasource and
  dashboard sidecars.

Signed-off-by: Ryan Probus <ryan.probus@appian.com>

2021-01-14 10:06 UTC, Xtigyro requested changes
Hey @ryanprobus - thanks for the contribution!
What added functionality does `labelValue` bring? Why `label` is not enough?

2021-01-14 15:16 UTC, ryanprobus commented
@Xtigyro While the intended functionality could be done with only `label`, that requires adding a label key that is non-standardized between different deployments. It would be nice if we could use a common label key and differentiate by the label value on which deployments should have which dashboards. Thought it would be nice to have the option of doing it this way.

2021-01-18 18:08 UTC, Xtigyro approved these changes

2021-01-18 18:10 UTC, Xtigyro commented
@ryanprobus OK - sounds useful. Thanks!

@zanhsieh @torstenwalter @maorfr Hmm, there's an issue with the code owners - I'm not picked as a reviewer.

2021-01-18 18:30 UTC, torstenwalter approved these changes

2021-01-18 18:31 UTC, merged