Hopefully this should fix Issue #1690
grafana/helm-charts pull request #1729
Opened 2022-08-25 18:09 UTC by sharkannon

2022-08-26 15:17 UTC, zanhsieh commented
@sharkannon 
Could you bump the version in Chart.yaml please?

2022-08-26 15:18 UTC, zanhsieh requested changes
@sharkannon
Could you bump the version in Chart.yaml please?

2022-08-28 00:03 UTC, sharkannon commented
@zanhsieh done, bumped the version by .1

2022-08-28 01:05 UTC, zanhsieh approved these changes

2022-08-28 01:43 UTC, merged