Remove deprecated api's to work with k8s 1.25.x
grafana/helm-charts pull request #1733
Opened 2022-08-26 11:29 UTC by d-e-a-n-f

Signed-off-by: Dean Foran <dean.foran@serverlessgroup.com>

2022-08-26 11:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=1733) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=1733) before we can accept your contribution.<br/><hr/>**Dean Foran** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=1733) it.</sub>

2022-08-27 03:18 UTC, zanhsieh requested changes
@d-e-a-n-f 
In case to make backward compatible, could you do following:

1. Append api version detection in `templates/_helper.tpl`:
```
{{- define "loki.podDisruptionBudget.apiVersion" -}}
  {{ if $.Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" -}}
    {{- print "policy/v1" -}}
  {{- else -}}
    {{- print "policy/v1beta1" -}}
  {{- end -}}
{{- end -}}

{{- define "loki.podSecurityPolicy.apiVersion" -}}
  {{ if .Capabilities.APIVersions.Has "policy/v1/PodSecurityPolicy" -}}
    {{- print "policy/v1" -}}
  {{- else -}}
    {{- print "policy/v1beta1" -}}
  {{- end -}}
{{- end -}}
```
2. Change `templates/pdb.yaml` line 2 as this:
```
apiVersion: {{ include "loki.podDisruptionBudget.apiVersion" . }}
```
3. Change `templates/podsecuritypolicy.yaml` line 2 as this:
```
apiVersion: {{ include "loki.podSecurityPolicy.apiVersion" . }}
```

4. Bump the Chart.yaml version to latest.

2022-08-27 12:24 UTC, d-e-a-n-f commented
> @d-e-a-n-f In case to make backward compatible, could you do following:
> 
> 1. Append api version detection in `templates/_helper.tpl`:
> 
> ```
> {{- define "loki.podDisruptionBudget.apiVersion" -}}
>   {{ if $.Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" -}}
>     {{- print "policy/v1" -}}
>   {{- else -}}
>     {{- print "policy/v1beta1" -}}
>   {{- end -}}
> {{- end -}}
> 
> {{- define "loki.podSecurityPolicy.apiVersion" -}}
>   {{ if .Capabilities.APIVersions.Has "policy/v1/PodSecurityPolicy" -}}
>     {{- print "policy/v1" -}}
>   {{- else -}}
>     {{- print "policy/v1beta1" -}}
>   {{- end -}}
> {{- end -}}
> ```
> 
>  2. Change `templates/pdb.yaml` line 2 as this:
> 
> ```
> apiVersion: {{ include "loki.podDisruptionBudget.apiVersion" . }}
> ```
> 
>  3. Change `templates/podsecuritypolicy.yaml` line 2 as this:
> 
> ```
> apiVersion: {{ include "loki.podSecurityPolicy.apiVersion" . }}
> ```
> 
>  4. Bump the Chart.yaml version to latest.

@zanhsieh  I have added the changes to the helper and it should now be backwards compatible. Pretty new to helm templates so unsure if the comment added on the _helper.tpl is ok with indentation and bullets.

2022-08-27 22:33 UTC, zanhsieh approved these changes

2022-08-27 22:39 UTC, merged