chore: support full metrics_generator config in tempo-distributed
grafana/helm-charts pull request #1750
Opened 2022-08-30 18:05 UTC by hobbsh

Adds support for the entire [metrics_generator config](https://grafana.com/docs/tempo/latest/configuration/#metrics-generator) in the `tempo-distributed` chart, matching the config structure. It looks like the `tempo` chart has a bit more of a bespoke configuration so I did not update that but I can if needed.

Addresses https://github.com/grafana/helm-charts/issues/1621

Important breaking change note:

- Moves `metricsGenerator.config.storage_remote_write` to `metricsGenerator.config.storage.remote_write`
- Moves `metricsGenerator.config.service_graphs_max_items` to `metricsGenerator.config.processor.service_graphs.max_items`

I can add these back to make things backwards compatible if needed. I only bumped a minor version but will bump a major if it's more appropriate, given the breaking change.

2022-08-30 18:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=1750) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=1750) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=1750) it.</sub>

2022-08-30 22:00 UTC, zanhsieh requested changes
@hobbsh 
Could you update README.md.gotmpl on `Upgrading` section for what would break over there? Please also regen README.md for review. Thank you.

For example,

```yaml
# README.md.gotml
...
## Upgrading

A major chart version change indicates that there is an incompatible breaking change needing manual actions.

### From chart version >= 0.26.0

Version 0.26.0:

- Moves metricsGenerator.config.storage_remote_write to metricsGenerator.config.storage.remote_write
- Moves metricsGenerator.config.service_graphs_max_items to metricsGenerator.config.processor.service_graphs.max_items

### From chart version < 0.23.0

Version 0.23.0:
...
```

2022-08-31 17:28 UTC, hobbsh commented on charts/tempo-distributed/values.yaml
> +        # Additional dimensions to add to the metrics. Dimensions are searched for in the
updated, thanks!

2022-09-01 07:20 UTC, faustodavid commented on charts/tempo-distributed/values.yaml
> +        # Additional dimensions to add to the metrics. Dimensions are searched for in the
Perfect, thanks! Please run helm-docs and commit the changes

2022-09-01 16:41 UTC, hobbsh commented on charts/tempo-distributed/values.yaml
> +        # Additional dimensions to add to the metrics. Dimensions are searched for in the
done!

2022-09-02 05:09 UTC, zanhsieh approved these changes

2022-09-02 05:10 UTC, merged

2022-09-02 07:20 UTC, faustodavid commented
Thanks for the contribution @hobbsh !