[loki-simple-scalable] Allows loki s3 http_config block to be configured
grafana/helm-charts pull request #1770
Opened 2022-09-02 13:51 UTC by j4rj4r

Fix for #1762 

This will allow users of the chart to configure the s3 http_config block as documented here [https://grafana.com/docs/loki/latest/configuration/#s3_storage_config](https://grafana.com/docs/loki/latest/configuration/#s3_storage_config) through values.

Signed-off-by: CAJNA Jarod <contact@jarodcajna.fr>

2022-09-02 13:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=1770) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=1770) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=1770) it.</sub>

2022-09-03 15:54 UTC, zanhsieh requested changes
@j4rj4r 
Could you rebase? It seems lots of files misalignment.

2022-09-03 16:22 UTC, j4rj4r commented
@zanhsieh  It's because of the change of repo of the loki-simple-scalable chart, no ? I made another merge request in the new repo [https://github.com/grafana/loki/pull/7041](https://github.com/grafana/loki/pull/7041)

2022-09-04 12:07 UTC, zanhsieh commented
@j4rj4r 
Yeap please. I close this one.

2022-09-04 12:07 UTC, closed without merging