[Grafana] - Add support for templating in ServiceMonitor namespace
grafana/helm-charts pull request #1774
Opened 2022-09-05 09:14 UTC by Allex1

2022-09-05 09:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=1774) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=1774) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=1774) it.</sub>

2022-09-06 07:56 UTC, zanhsieh requested changes

2022-09-06 07:56 UTC, zanhsieh commented on charts/grafana/templates/servicemonitor.yaml
> +  namespace: {{ tpl (.Values.serviceMonitor.namespace) . }}
Extra bracket is not needed.

```suggestion
  namespace: {{ tpl .Values.serviceMonitor.namespace . }}
```

2022-09-06 09:21 UTC, Allex1 commented
@zanhsieh PTAL

2022-09-06 09:57 UTC, zanhsieh approved these changes

2022-09-06 09:57 UTC, merged