[promtail] Adding serviceMonitor scheme and tlsConfig values
grafana/helm-charts pull request #1813
Opened 2022-09-14 14:25 UTC by rgarcia6520

Signed-off-by: garcia.ryan <garcia.ryan@solute.us>

Adding `scheme` & `tlsConfig` values to `serviceMonitor` for promtail.

2022-10-24 11:11 UTC, verejoel commented
Didn't see this before I submitted #1918, really need this TLS config change in

2022-10-25 02:30 UTC, zanhsieh requested changes

2022-10-25 02:30 UTC, zanhsieh commented on charts/promtail/templates/servicemonitor.yaml
> +      {{- end }}
```suggestion
      {{- with .Values.serviceMonitor.tlsConfig }}
      tlsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```

2022-10-25 08:30 UTC, verejoel commented on charts/promtail/templates/servicemonitor.yaml
>  {{- end }}
```suggestion
  {{- with .targetLabels }}
  targetLabels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
```

2022-10-25 08:32 UTC, verejoel commented on charts/promtail/values.yaml
>    metricRelabelings: []
```suggestion
  metricRelabelings: []
    # --ServiceMonitor will add labels from the service to the Prometheus metric
  # https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#servicemonitorspec
  targetLabels: []
```

2022-11-12 00:01 UTC, zanhsieh commented
It seems this PR already superseded by other PRs. Close it for now.

2022-11-12 00:01 UTC, closed without merging