[Tempo] Load environment variables from Secrets
grafana/helm-charts pull request #1930
Opened 2022-10-27 11:04 UTC by nlamirault

Like in Tempo Distributed chart , Loki chart, ...

2022-10-27 11:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=1930) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=1930) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=1930) it.</sub>

2022-10-27 17:56 UTC, BitProcessor requested changes
Hi @nlamirault, thanks for your contribution 🚀 
Please bump the chart version and update the helm-docs.

2022-10-29 14:55 UTC, zanhsieh requested changes

2022-10-29 14:55 UTC, zanhsieh commented on charts/tempo/templates/statefulset.yaml
> +        {{- end }}
```suggestion
        {{- with .Values.tempo.extraEnvFrom }}
        envFrom:
          {{- toYaml . | nindent 10 }}
        {{- end }}
```

2022-10-29 16:54 UTC, zanhsieh requested changes

2022-10-29 16:54 UTC, zanhsieh commented on charts/tempo/templates/statefulset.yaml
>            {{- end }}
```suggestion
          {{- with .Values.tempo.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
```

2022-10-31 10:15 UTC, BitProcessor submitted a review, later dismissed
Please update the helm docs

2022-11-03 09:28 UTC, zanhsieh approved these changes

2022-11-16 00:34 UTC, merged