[promtail] update to promtail version 2.7.0
grafana/helm-charts pull request #2026
Opened 2022-11-30 09:11 UTC by gasmick

Updating the helm chart given the new release
![image](https://user-images.githubusercontent.com/33287410/204754661-10f5b865-4368-4b88-8ab4-01b36c3a6075.png)

2022-11-30 09:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2026) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2026) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2026) it.</sub>

2022-12-02 11:45 UTC, zanhsieh requested changes
@gasmick 
Thank you for contribution. Do you mind to write what the user has to know while upgrading from 2.6.x to 2.7.0 in READNE.md.tpl?

2022-12-02 15:09 UTC, gasmick commented
@zanhsieh Thank you for taking the time. I don't see anything relevant for the Helm chart in the [Upgrading](https://grafana.com/docs/loki/next/upgrading/#promtail-1) documentation to explicitly mention here.

2022-12-02 15:51 UTC, zanhsieh approved these changes

2022-12-02 15:51 UTC, merged