Fix for invalid labels
grafana/helm-charts pull request #2067
Opened 2022-12-15 10:11 UTC by kvanzuijlen

When using SHA hashes in image tags, kubernetes rejects the resource with the following error message:
`<resource> is invalid: [metadata.labels: Invalid value: "<version@hash>": must be no more than 63 characters, metadata.labels: Invalid value: "<version@hash>": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]`

2022-12-15 10:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2067) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2067) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2067) it.</sub>

2022-12-26 17:54 UTC, zanhsieh commented
@kvanzuijlen 
Thank you for contribution. Could you bump the version in Chart.yaml please?

2022-12-26 17:57 UTC, zanhsieh requested changes
@kvanzuijlen
Thank you for contribution. Could you bump the version in Chart.yaml please?

2022-12-26 20:05 UTC, kvanzuijlen commented
I seem to have fat-fingered the reviewers on my phone :(

2022-12-27 01:34 UTC, zanhsieh approved these changes

2022-12-27 01:35 UTC, zanhsieh approved these changes

2022-12-27 01:35 UTC, merged