[grafana] Allow to configure HPA scaling behavior and add autoscaling for grafana-image-renderer
grafana/helm-charts pull request #2081
Opened 2022-12-28 03:34 UTC by peikk0

* Update the `grafana.hpa.apiVersion` helper to support the `autoscaling/v2beta2` API
* Update the Grafana HPA to allow configuring scaling behavior
* Add optional autoscaling for the `grafana-image-renderer`deployment

2022-12-28 03:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2081) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2081) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2081) it.</sub>

2022-12-28 13:21 UTC, zanhsieh requested changes
@peikk0 
How did you test HPA work? Any stress test to introduce in ci to proof HPA implementation work?

2022-12-29 03:53 UTC, peikk0 commented
@zanhsieh 

> How did you test HPA work? Any stress test to introduce in ci to proof HPA implementation work?

I'm not sure how best to test this in CI, however we have been using those HPAs in production for close to a year now without any issue. This is from a custom Tanka/jsonnet deployment instead of this helm Chart though (and I'm working on migrating it from Tanka to Helm, hence this patch), but the resulting HPA and deployment are the same:

* https://gitlab.com/gitlab-com/gl-infra/k8s-workloads/tanka-deployments/-/blob/master/lib/gl-grafana/grafana.libsonnet#L200-221
* https://gitlab.com/gitlab-com/gl-infra/k8s-workloads/tanka-deployments/-/blob/master/lib/gl-grafana/grafana.libsonnet#L400-421

![image](https://user-images.githubusercontent.com/1555947/209900956-7fcc68b4-ff47-42a5-b34a-248b1a22abef.png)

I have also tested that it applies cleanly, with HPA enabled and disabled, and behavior set and unset.

> Also please bump the version in Chart.yaml.

Version bumped.

2022-12-29 13:54 UTC, zanhsieh approved these changes

2023-01-10 00:45 UTC, peikk0 commented
@zanhsieh I've rebased the branch and bumped the version again following the merge of https://github.com/grafana/helm-charts/pull/2083

2023-01-10 15:45 UTC, merged