[grafana] Add a ServiceMonitor for grafana-image-renderer
grafana/helm-charts pull request #2083
Opened 2022-12-29 07:24 UTC by peikk0

* Add a ServiceMonitor for `grafana-image-renderer`
* Allow adding extra selectors to the `grafana-image-renderer` ingress network policy so that the Prometheus Operator can be allowed to query the metrics

2022-12-29 14:06 UTC, zanhsieh requested changes

2022-12-29 14:06 UTC, zanhsieh commented on charts/grafana/templates/image-renderer-network-policy.yaml
> +        {{- end }}
```suggestion
        {{- with .Values.imageRenderer.networkPolicy.extraIngressSelectors -}}
        {{ toYaml . | nindent 8 }}
        {{- end }}
```

2022-12-30 14:45 UTC, zanhsieh commented
@peikk0 
Thank you for the contribution. Could you bump the version to latest in Chart.yaml please?

2023-01-02 01:10 UTC, peikk0 commented
@zanhsieh Chart version bumped. 👍🏻

2023-01-02 04:14 UTC, zanhsieh approved these changes

2023-01-02 04:14 UTC, merged