Update query-fronted service to set clusterIP
grafana/helm-charts pull request #2110
Opened 2023-01-11 18:41 UTC by philipschwartz-okta

Documentation suggests using clusterIP=None to fix issues with startup race conditions between query-frontend and queriers.

This change sets this value by default.

Signed-off-by: Philip Schwartz <philip.schwartz@okta.com>

2023-01-11 18:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2110) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2110) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2110) it.</sub>

2023-01-11 22:23 UTC, zanhsieh commented
@philipschwartz-okta 
Thanks for the contribution. Could you bump the version in Chart.yaml please?

2023-01-11 22:23 UTC, zanhsieh requested changes
@philipschwartz-okta
Thanks for the contribution. Could you bump the version in Chart.yaml please?

2023-01-12 02:02 UTC, zanhsieh approved these changes

2023-01-12 02:02 UTC, merged

2023-01-16 11:58 UTC, Siebjee commented
Can we revert this change? Helm now fails for existing chart deployments:
https://github.com/grafana/helm-charts/issues/2127