[tempo-distributed] add headless service for tempo-distributor
grafana/helm-charts pull request #2139
Opened 2023-01-20 11:00 UTC by AlphaStyle

This merge request will add a [headless service](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services) for the tempo-distributor.

When the OpenTelemetry Collector is using the [Load Balancing Exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/loadbalancingexporter/README.md), and the load balancing exporter is configured to used the `dns` resolver, a headless service for the tempo-distributor is required for the dns resolver to get all endpoints. Without a headless service, the load balancing exporter will only see the Kubernetes service IP, and not the endpoints.

If you have suggestions, improvements or questions, feel free to ask or enlighten me.

2023-01-20 11:44 UTC, mapno commented
You can also export via HTTP and send traces to [these endpoints](https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/values.yaml#L1384-L1394), and the gateway will handle the load balancing. I'm ok with merging this as well if needed.

2023-01-20 13:05 UTC, AlphaStyle commented
We just tried what you suggested. Setting up a `otelhttp` exporter in OpenTelemetry Collector and using the tempo-gateway as the endpoint does indeed work as you said.

The advantage with this Pull Request is that you can also load balance grpc. Just for the sake of alternatives, I would like to continue with the pull request :+1:

2023-01-23 14:54 UTC, mapno approved these changes
Agree, we can add this as an alternative.

2023-01-24 07:40 UTC, AlphaStyle commented on charts/tempo-distributed/templates/distributor/service-distributor-discovery.yaml
> +      {{- end }}
Did a rebase, and removed `9095` port from the headless distributor service :+1:

2023-01-25 00:24 UTC, zanhsieh requested changes

2023-01-25 00:24 UTC, zanhsieh commented on charts/tempo-distributed/Chart.yaml
> +version: 0.27.20
Feature added should be bumped to minor version.
```suggestion
version: 0.28.0
```

2023-01-25 00:24 UTC, zanhsieh commented on charts/tempo-distributed/README.md
> +![Version: 0.27.20](https://img.shields.io/badge/Version-0.27.20-informational?style=flat-square) ![Type: application](https://img.shields.io/badge/Type-application-informational?style=flat-square) !
```suggestion
![Version: 0.28.0](https://img.shields.io/badge/Version-0.28.0-informational?style=flat-square) ![Type: application](https://img.shields.io/badge/Type-application-informational?style=flat-square) ![AppVersion: 1.5.0](https://img.shields.io/badge/AppVersion-1.5.0-informational?style=flat-square)
```

2023-01-25 00:30 UTC, zanhsieh approved these changes

2023-01-25 00:30 UTC, merged