[grafana chart] H/A gossip port bug fix
grafana/helm-charts pull request #2146
Opened 2023-01-24 07:50 UTC by haileymoon

* The guide for H/A defines ha_peers port as 9094
* https://github.com/grafana/helm-charts/tree/main/charts/grafana#high-availability-for-unified-alerting
ISSUE:
* When i set the ha_peers value as {{ Name }}-headless:9094, i get a lookup error. 
* I also get an (failed to join)error when i set it to port 3000 
* I've made changes to my helm-generated-yaml and i don't get the error log anymore, and is working as intended. I applied the changes i made to the chart. please review! thanks

2023-01-24 07:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2146) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2146) before we can accept your contribution.<br/><hr/>**haileymoon** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2146) it.</sub>

2023-01-24 14:19 UTC, zanhsieh requested changes
@haileymoon 
Thank you for the contribution. Could you sign CLA as showing on the bottom of this PR page please?

2023-01-25 01:20 UTC, haileymoon commented
> @haileymoon Thank you for the contribution. Could you sign CLA as showing on the bottom of this PR page please?

Signed it! Thanks

2023-01-25 08:11 UTC, zanhsieh approved these changes

2023-01-25 08:11 UTC, merged