[grafana] option to allow optional args
grafana/helm-charts pull request #2160
Opened 2023-01-27 20:05 UTC by gietschess

when its possible to set a alternative `command` for the grafana container, it should also be possible to set `args` for this command.
would be useful when using hashicorp/envconsul.

Signed-off-by: gietschess <49275246+gietschess@users.noreply.github.com>

2023-01-27 20:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2160) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2160) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2160) it.</sub>

2023-01-30 21:46 UTC, zanhsieh requested changes

2023-01-30 21:47 UTC, zanhsieh requested changes
Please also bump the version in Chart.yaml to latest. Thank you.

2023-01-31 07:01 UTC, gietschess commented on charts/grafana/values.yaml
> +# args:
@zanhsieh you're right, forgot to remove the comment after testing it locally.

2023-01-31 09:06 UTC, gietschess commented on charts/grafana/values.yaml
> +# args:
@zanhsieh  this should not be needed.
similar to command args should only be created in the _pod.tpl when the values is set.

2023-02-03 01:31 UTC, zanhsieh approved these changes

2023-02-03 01:31 UTC, merged