[fluent-bit] Add support for securityContext
grafana/helm-charts pull request #2165
Opened 2023-01-30 08:53 UTC by Garnaalkroket

In order to comply with certain audit policies I'd like to set a securityContext on the  fluent-bit pod.
It seems in the past a podSecurityPolicy was supplied, but that mechanism is deprecated now.
Would it be possible to add this support?

Kind regards,
Robin

2023-01-30 08:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2165) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2165) before we can accept your contribution.<br/><hr/>**Robin De Roeck** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2165) it.</sub>

2023-01-31 02:45 UTC, zanhsieh requested changes
Please bump the version in Chart.yaml. Thank you.

2023-01-31 02:45 UTC, zanhsieh commented on charts/fluent-bit/templates/daemonset.yaml
> +      {{- end}}
```suggestion
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .| nindent 8 }}
      {{- end}}
```

2023-01-31 02:45 UTC, zanhsieh commented on charts/fluent-bit/templates/daemonset.yaml
> +          {{- end }}
```suggestion
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
```

2023-02-02 09:21 UTC, Garnaalkroket commented on charts/fluent-bit/templates/daemonset.yaml
> +      {{- end}}
Thanks! Should be fixed.

2023-02-02 12:41 UTC, zanhsieh requested changes
Please sign DCO. Thanks. For instruction please see the bottom of this PR page `Details` next to `DCO Action required after 1s — DCO`.

2023-02-02 13:06 UTC, closed without merging