[promtail] Implement config-reloader
grafana/helm-charts pull request #2187
Opened 2023-02-07 21:50 UTC by jkroepke

Hi,

on large clusters, the rollout of promtail could take some time. This PR extends the current helm chart by an config reloader sidecar. It depends on https://github.com/grafana/loki/pull/7247.

I used the config-reloader images from prometheus helm chart. config-reloader implements inotify to detect changes instantly.

2023-02-09 22:13 UTC, jkroepke commented
@zanhsieh Are you able to give feedback on this?

2023-02-17 23:24 UTC, zanhsieh requested changes
@jkroepke 
Is there anything the user should know for upgrading to minor version? If yes, should that be explain in the README.md.gotmpl?

2023-02-17 23:56 UTC, jkroepke commented
Hi @zanhsieh 

no. This feature is opt-in. On update, without any changes to values.yaml. nothing would be changed on user side.

2023-02-19 15:24 UTC, zanhsieh approved these changes

2023-02-19 15:24 UTC, merged