Allow setting persistentVolumeReclaimPolicy for persistent volume
grafana/helm-charts pull request #2237
Opened 2023-03-01 07:35 UTC by kosta

In the default configuration (using deployment instead of statefulset), a pod eviction can delete the persistent volume. Using StatefulSet helps somewhat, but I can sleep better at night if I know that my grafana persistent volume is not easily accidentally deleted. (This keeps the kubernetes default of `Delete` but can be set to e.g. `Retain`)

2023-03-03 21:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2237) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2237) before we can accept your contribution.<br/><hr/>**Kosta Welke** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2237) it.</sub>

2023-03-06 01:13 UTC, zanhsieh requested changes
@kosta 
Thanks for the contribution. Could you bump the version in Chart.yaml and sign DCO please?

2023-03-08 14:12 UTC, kosta commented
I signed the CLA and bumped the helm chart version. Let me know if there's anything else I can do to move this forward :)

2023-03-09 10:52 UTC, kosta commented
Pushed the same code, but rebased on main with a single commit that has the required DCO.

2023-03-11 01:02 UTC, zanhsieh approved these changes

2023-03-11 08:03 UTC, merged