[grafana] bumped grafana version to 9.4.3
grafana/helm-charts pull request #2249
Opened 2023-03-03 11:38 UTC by sherifkayad

bumped Grafana to the latest version `9.4.3` released on the 2nd of March, 2023 (https://github.com/grafana/grafana/blob/main/CHANGELOG.md)

2023-03-03 17:14 UTC, zanhsieh requested changes
.

2023-03-03 17:24 UTC, zanhsieh requested changes
@sherifkayad
Please don't replace README.md unless it's ready for backward compatible.

2023-03-06 08:45 UTC, sherifkayad commented
@zanhsieh done! could you please have another look?

2023-03-07 05:05 UTC, zanhsieh approved these changes

2023-03-07 05:06 UTC, merged