Add automountServiceAccountToken variable to fluent-bit
grafana/helm-charts pull request #2288
Opened 2023-03-23 13:56 UTC by stgrace

2023-03-23 13:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2288) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2288) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2288) it.</sub>

2023-03-24 03:19 UTC, zanhsieh requested changes
@stgrace 
Thanks for the contribution. Couple things:
- Could you describe why we need this PR by updating the PR description?
- Since this PR advance a minor version, could you update README.md that describes what would the impact for the old version user for upgrading? e.g. upgrade procedure, incompatibilities, etc.

2023-03-31 12:03 UTC, stgrace commented
Hi @zanhsieh,

I updated the README and the description. If any other info is needed, please let me know.

2023-03-31 15:03 UTC, zanhsieh approved these changes

2023-03-31 15:03 UTC, merged