[grafana] add ingressClassName information
grafana/helm-charts pull request #2304
Opened 2023-03-28 13:23 UTC by juris

`ingressClassName` info is available in other helm charts but was missing in Grafana chart

2023-03-28 13:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2304) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2304) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2304) it.</sub>

2023-03-31 23:29 UTC, zanhsieh requested changes
@juris 
Thank you for the contribution. Could you bump the version in Chart.yaml file to latest? Without version bumped, the CI won't allow to merge to master.

2023-04-04 16:08 UTC, juris commented
> @juris Thank you for the contribution. Could you bump the version in Chart.yaml file to latest? Without version bumped, the CI won't allow to merge to master.

Bumped. Thank you!

2023-04-04 18:07 UTC, zanhsieh approved these changes

2023-04-04 18:07 UTC, merged