[grafana] RBAC rules for alerting sidecar
grafana/helm-charts pull request #2307
Opened 2023-03-29 14:51 UTC by juris

If you enable just an alerting sidecar, it won't work as there are no RBAC rules for it.

2023-03-31 07:48 UTC, zanhsieh requested changes
@juris 
Thanks for the contribution. Please bump the version in Chart.yaml otherwise CI won't allow to merge.

2023-04-04 16:04 UTC, juris commented
> @juris Thanks for the contribution. Please bump the version in Chart.yaml otherwise CI won't allow to merge.

Bumped to the next one. Cheers!

2023-04-04 18:35 UTC, zanhsieh requested changes

2023-04-04 18:35 UTC, zanhsieh commented on charts/grafana/templates/clusterrole.yaml
> +{{- if or .Values.sidecar.dashboards.enabled (or .Values.rbac.extraClusterRoleRules (or .Values.sidecar.datasources.enabled (or .Values.sidecar.plugins.enabled .Values.sidecar.alerts.enabled))) }}
```suggestion
{{- if or .Values.sidecar.dashboards.enabled .Values.rbac.extraClusterRoleRules .Values.sidecar.datasources.enabled .Values.sidecar.plugins.enabled .Values.sidecar.alerts.enabled }}
```

2023-04-04 18:35 UTC, zanhsieh commented on charts/grafana/templates/clusterrole.yaml
> +  {{- if or .Values.sidecar.dashboards.enabled (or .Values.sidecar.datasources.enabled (or .Values.sidecar.plugins.enabled .Values.sidecar.alerts.enabled)) }}
```suggestion
  {{- if or .Values.sidecar.dashboards.enabled .Values.sidecar.datasources.enabled .Values.sidecar.plugins.enabled .Values.sidecar.alerts.enabled }}

2023-04-04 19:21 UTC, zanhsieh approved these changes

2023-04-04 19:21 UTC, merged