[rollout-operator]: add podLabels to deployment
grafana/helm-charts pull request #2313
Opened 2023-03-30 20:39 UTC by akorp

Closes: https://github.com/grafana/helm-charts/issues/2311

2023-04-07 10:17 UTC, boniek83 commented
Please sign CLA by clicking on any link in CLAassistant's comment, bump version to 0.4.2 and regenerate README.md by running helm-docs.

2023-04-07 12:46 UTC, zanhsieh requested changes

2023-04-07 12:46 UTC, zanhsieh commented on charts/rollout-operator/templates/deployment.yaml
> +        { { - end } }
```suggestion
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
```

2023-04-11 19:57 UTC, akorp commented
> @akorp Thanks for the contribution. Would you mind to sign CLA so the CI could merge this PR please?

@zanhsieh done

2023-04-12 08:31 UTC, merged