fixed RBAC configurations to match the values.yaml
grafana/helm-charts pull request #2320
Opened 2023-04-01 12:39 UTC by uya116

resolves #2316 

fixed RBAC configurations in README to match the values.yaml

2023-04-01 12:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2320) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2320) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2320) it.</sub>

2023-04-01 14:19 UTC, zanhsieh requested changes
@uya116 
Thank you for the contribution. Would you mind to bump the version in Charts.yaml to latest so CI could pass and merge it later on please?

2023-04-03 01:06 UTC, uya116 commented
> @uya116 Thank you for the contribution. Would you mind to bump the version in Charts.yaml to latest so CI could pass and merge it later on please?

Thank you for your review. i bumped Chart version. is it OK ?

2023-04-03 01:52 UTC, zanhsieh approved these changes

2023-04-03 01:52 UTC, merged