[grafana] set security controls for pod-security-standards restricted
grafana/helm-charts pull request #2340
Opened 2023-04-11 22:24 UTC by jcpunk

This adds the missing controls to permit the `grafana` container to run under https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted

2023-04-11 22:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2340) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2340) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2340) it.</sub>

2023-04-12 07:48 UTC, zanhsieh requested changes
@jcpunk 
Thank you for the contribution. Would you mind to bump the version in Chart.yaml so the CI could merge to the master?

2023-04-13 13:16 UTC, jcpunk commented
PR updated

2023-04-14 01:53 UTC, zanhsieh requested changes

2023-04-14 01:53 UTC, zanhsieh commented on charts/grafana/values.yaml
> +    - ALL
@jcpunk 
Some error on CI:
```text
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.securityContext): unknown field "capabilities" in io.k8s.api.core.v1.PodSecurityContext
```

2023-04-15 00:51 UTC, zanhsieh approved these changes

2023-04-15 00:52 UTC, merged