[tempo-distributed] add ingress for jaeger ui in tempo distributed chart
grafana/helm-charts pull request #2361
Opened 2023-04-23 11:53 UTC by yonahd

Signed-off-by: ydissen <yonahdissen@gmail.com>

2023-04-23 11:54 UTC, yonahd commented
@zanhsieh This is the tempo-distibuted part of the PR https://github.com/grafana/helm-charts/pull/2347

2023-04-23 15:45 UTC, zanhsieh requested changes

2023-04-23 15:45 UTC, zanhsieh commented on charts/tempo-distributed/templates/query-frontend/ingress-query-frontend.yaml
> +{{- if .Values.queryFrontend.ingress.enabled -}}
```suggestion
{{- if and .Values.queryFrontend.query.enabled .Values.queryFrontend.ingress.enabled -}}
```

2023-04-23 15:45 UTC, zanhsieh commented on charts/tempo-distributed/templates/query-frontend/ingress-query-frontend.yaml
> +{{- end }}
```suggestion
{{- end }}
```

2023-04-24 00:19 UTC, zanhsieh approved these changes

2023-04-24 00:19 UTC, merged