[grafana] Add envValueFrom to image-renderer
grafana/helm-charts pull request #2391
Opened 2023-05-08 06:51 UTC by Red-M

This allows using secrets or configmaps in-cluster to configure options for the image-renderer.
This is useful for setting the renderer token via an in-cluster secret.
From grafana/grafana-image-renderer#420

2023-05-08 06:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2391) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2391) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2391) it.</sub>

2023-05-08 13:57 UTC, zanhsieh requested changes
@Red-M 
Thank you for the contribution. Would you mind to bump the version in Chart.yaml to latest so the CI can merge this PR once approved?

2023-05-09 04:20 UTC, Red-M commented
Done

2023-05-09 05:26 UTC, zanhsieh approved these changes

2023-05-09 05:27 UTC, merged