[promtail] bump promtail version to 2.8.2
grafana/helm-charts pull request #2392
Opened 2023-05-09 09:19 UTC by antonincms

As it seems there are no breaking changes concerning promtail between 2.7.4 and 2.8.2, 
this PR aim to bump promtail version (resolves #2379).

2023-05-09 13:35 UTC, zanhsieh requested changes
@antonincms 
Thanks for the contribution. Since this PR bumped the minor version, could you write down what the user should know for upgrading from 6.11.x to 6.12.x in README.md.tpl / README.md? E.g. what would break the upgrade? procedure to upgrade without data loss?

2023-05-09 15:07 UTC, antonincms commented
From what I [linked in the issue](https://github.com/grafana/loki/blob/main/CHANGELOG.md#282-2023-05-03), it seems there are no breaking changes concerning promtail between these versions, only fixes, improvements and additions :  

<details><summary>Changelog extract</summary>
<p>

```
## 2.8.2 (2023-05-03)

#### Promtail

##### Enhancements

* 8994 **DylanGuedes**: Promtail: Add new `decompression` configuration to customize the decompressor behavior.

## 2.8.1 (2023-04-24)

#### Promtail

##### Fixes

* 9095 **JordanRushing** Fix journald support in amd64 binary build.

## 2.8.0 (2023-04-04)

#### Promtail

##### Enhancements

* 8231 **CCOLLOT**: Lambda-promtail: add support for AWS SQS message ingestion.
* 7619 **cadrake**: Add ability to pass query params to heroku drain targets for relabelling.
* 7973 **chodges15**: Add configuration to drop rate limited batches in Loki client and new metric label for drop reason.
* 8153 **kavirajk**: promtail: Add `max-line-size` limit to drop on client side
* 8096 **kavirajk**: doc(promtail): Doc about how log rotate works with promtail
* 8233 **nicoche**: promtail: Add `max-line-size-truncate` limit to truncate too long lines on client side
* 7462 **MarNicGit**: Allow excluding event message from Windows Event Log entries.
* 7597 **redbaron**: allow ratelimiting by label
* 3493 **adityacs** Support geoip stage.
* 8382 **kelnage**: Promtail: Add event log message stage

##### Fixes

* 8231 **CCOLLOT**: Lambda-promtail: fix flushing behavior of batches, leading to a significant increase in performance.
```

</p>
</details> 

I don't think there is anything breaking, should I have bump the patch version instead ?

2023-05-10 07:20 UTC, zanhsieh commented
> 

Bump the patch version should be fine. Thank you.

2023-05-10 09:15 UTC, zanhsieh approved these changes

2023-05-10 09:15 UTC, merged