Update tempo-distributed to have metrics_ingestion_time_range_slack
grafana/helm-charts pull request #2433
Opened 2023-05-26 21:02 UTC by EStork09

metrics_ingestion_time_range_slack = 30s is the default and added to the tempo configuration

2023-05-26 21:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2433) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2433) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2433) it.</sub>

2023-06-22 04:38 UTC, zanhsieh requested changes
@EStork09 
Thanks for the contribution. Can you bump the version in Chart.yaml to latest? So later CI can merge this PR once approved.

2023-06-23 04:11 UTC, EStork09 commented
@zanhsieh I synced my fork with main, let me know if there is anything else!

2023-06-23 09:53 UTC, zanhsieh approved these changes

2023-06-23 09:53 UTC, merged