fix tempo distributor deployment otlp-http port
grafana/helm-charts pull request #2454
Opened 2023-06-08 11:31 UTC by Kangkeizai

2023-06-08 11:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2454) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2454) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2454) it.</sub>

2023-06-22 04:33 UTC, zanhsieh requested changes
@Kangkeizai 
Thanks for the contribution. Can you bump the version in Chart.yaml to latest? So later CI can merge this PR once the maintainer approved.

2023-06-27 11:56 UTC, Kangkeizai commented
> 

Thanks for the reminder, I've done it.

2023-06-29 01:26 UTC, zanhsieh approved these changes

2023-06-29 01:26 UTC, merged