Add support for custom ingress rules on query-frontend
grafana/helm-charts pull request #2526
Opened 2023-07-24 11:26 UTC by pedro93

Allows the possibility for the query frontend ingress controller to expose specific ports and not be tied to Jaeger UI.

2023-07-24 11:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2526) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2526) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2526) it.</sub>

2023-08-04 07:35 UTC, zanhsieh requested changes
@pedro93 
Thanks for the contribution. Can you fix the lint error and sign DCO please?

2023-08-08 15:13 UTC, pedro93 commented
I worked around this by using the gateway resource so ended up not needing this change. If it still makes sense feel free to merge it in.

2023-08-08 20:09 UTC, zalegrala commented
I'm inclined to leave it out unless someone else from the community sees a potential need.  Any takers?

2024-01-12 02:52 UTC, closed without merging