Host aliases for enterprise logs
grafana/helm-charts pull request #2541
Opened 2023-07-26 10:02 UTC by YuleZ

I need to set hostAliases in my environment for loki-distributed.
This PR adds this feature to the other helm-charts as well as for loki-distributed where I need this change initially.

2023-07-26 15:12 UTC, zanhsieh requested changes

2023-07-26 15:12 UTC, zanhsieh commented on charts/enterprise-logs/values.yaml
> +  hostAliases: [ ]
```suggestion
  hostAliases: []
```

2023-07-26 15:12 UTC, zanhsieh commented on charts/enterprise-logs/values.yaml
> +  hostAliases: [ ]
```suggestion
  hostAliases: []
```

2023-07-26 15:12 UTC, zanhsieh commented on charts/enterprise-logs/values.yaml
> +  hostAliases: [ ]
```suggestion
  hostAliases: []
```

2023-07-26 15:12 UTC, zanhsieh commented on charts/enterprise-logs/values.yaml
> +  hostAliases: [ ]
```suggestion
  hostAliases: []
```

2023-09-05 07:05 UTC, YuleZ commented
@zanhsieh can you check what's wrong with the lint-test job? Looks like a connectivity issue inside the test. I don't think this relate to my changes.

2023-09-05 07:17 UTC, zanhsieh commented
@YuleZ 
I did try to figure it out but still puzzling. No idea why helm add minio repo would fail.

2023-09-05 10:02 UTC, zanhsieh commented
@YuleZ Can you rebase this PR please? It seems this PR does not recognize ct.yaml change.

2023-09-10 15:04 UTC, zanhsieh approved these changes

2023-09-10 15:04 UTC, merged