Host aliases for fluent bit
grafana/helm-charts pull request #2544
Opened 2023-07-26 11:11 UTC by YuleZ

I need to set hostAliases in my environment for loki-distributed.
This PR adds this feature to the other helm-charts as well as for loki-distributed where I need this change initially.

2023-07-27 06:11 UTC, zanhsieh requested changes

2023-07-27 06:11 UTC, zanhsieh commented on charts/fluent-bit/values.yaml
> +hostAliases: [ ]
```suggestion
hostAliases: []
```

2023-07-31 02:00 UTC, zanhsieh requested changes
@YuleZ 
The final step: Sign DCO. Thanks.

2023-08-01 11:25 UTC, YuleZ commented
> @YuleZ
> The final step: Sign DCO. See the bottom of this page next to DCO for instructions (click Details). Thanks.


I believe this fails because I used Github's possibility to apply suggestions made by you via the webUI where it cannot be signed correctly. I think I have to put this PR together again.

2023-08-01 11:29 UTC, zanhsieh approved these changes

2023-08-01 11:29 UTC, merged