Host aliases for tempo distributed
grafana/helm-charts pull request #2549
Opened 2023-07-26 11:28 UTC by YuleZ

I need to set hostAliases in my environment for loki-distributed.
This PR adds this feature to the other helm-charts as well as for loki-distributed where I need this change initially.

2023-07-27 21:27 UTC, zalegrala approved these changes
This looks good to me, thanks for putting this together.

2023-07-28 16:40 UTC, zalegrala commented
The CI is failing with some details.  Let me know if you have a chance to review.

2023-07-29 01:47 UTC, zanhsieh requested changes

2023-07-29 01:47 UTC, zanhsieh commented on charts/tempo-distributed/values.yaml
> +  hostAliases: [ ]
```suggestion
  hostAliases: []
```

2023-07-29 01:47 UTC, zanhsieh commented on charts/tempo-distributed/values.yaml
> +  hostAliases: [ ]
```suggestion
  hostAliases: []
```

2023-07-29 01:47 UTC, zanhsieh commented on charts/tempo-distributed/values.yaml
> +  hostAliases: [ ]
```suggestion
  hostAliases: []
```

2023-07-29 01:47 UTC, zanhsieh commented on charts/tempo-distributed/values.yaml
> +  hostAliases: [ ]
```suggestion
  hostAliases: []
```

2023-07-29 01:47 UTC, zanhsieh commented on charts/tempo-distributed/values.yaml
> +  hostAliases: [ ]
```suggestion
  hostAliases: []
```

2023-07-29 01:47 UTC, zanhsieh commented on charts/tempo-distributed/values.yaml
> +  hostAliases: [ ]
```suggestion
  hostAliases: []
```

2023-07-29 01:47 UTC, zanhsieh commented on charts/tempo-distributed/values.yaml
> +  hostAliases: [ ]
```suggestion
  hostAliases: []
```

2023-07-29 01:47 UTC, zanhsieh commented on charts/tempo-distributed/values.yaml
> +  hostAliases: [ ]
```suggestion
  hostAliases: []
```

2023-07-29 01:47 UTC, zanhsieh commented on charts/tempo-distributed/values.yaml
> +  hostAliases: [ ]
```suggestion
  hostAliases: []
```

2023-07-29 01:47 UTC, zanhsieh commented on charts/tempo-distributed/values.yaml
> +  hostAliases: [ ]
```suggestion
  hostAliases: []
```

2023-07-29 01:47 UTC, zanhsieh commented on charts/tempo-distributed/values.yaml
> +  hostAliases: [ ]
```suggestion
  hostAliases: []
```

2023-07-29 01:47 UTC, zanhsieh commented on charts/tempo-distributed/values.yaml
> +  hostAliases: [ ]
```suggestion
  hostAliases: []
```

2023-08-01 03:16 UTC, zanhsieh approved these changes

2023-08-01 03:16 UTC, merged