[promtail] feat: add vpa support
grafana/helm-charts pull request #2551
Opened 2023-07-26 16:08 UTC by t3mi

2023-07-26 18:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2551) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2551) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2551) it.</sub>

2023-07-31 02:04 UTC, zanhsieh requested changes
@t3mi 
Thank you for the contribution. Can you fix the document errors in README.md (use helm-docs to generate new README.md, and then commit to this PR)?

2023-07-31 06:35 UTC, t3mi commented
@zanhsieh ofc, added.

2023-08-01 03:34 UTC, zanhsieh approved these changes

2023-08-01 03:34 UTC, merged