[tempo-distributed] Querier readiness probe
grafana/helm-charts pull request #2556
Opened 2023-07-28 08:39 UTC by coufalja

Querier is missing the readiness probe which causes the downtime of query path each time the deployment is rolled out.

2023-07-28 08:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2556) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2556) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2556) it.</sub>

2023-07-28 19:01 UTC, zalegrala commented
This looks good to me, thanks for the contribution.  Can you bump the version to make CI happy?

2023-07-28 19:39 UTC, coufalja commented
Sure thing 👍

2023-07-31 18:22 UTC, zalegrala commented
I failed to come back to github soon enough last week.  Going to take https://github.com/grafana/helm-charts/pull/2560 first, and then you'll need to bump the version again after rebase.  I'll keep an eye today and will get this in quickly after the update.

2023-08-01 09:50 UTC, zanhsieh requested changes

2023-08-01 09:50 UTC, zanhsieh commented on charts/tempo-distributed/templates/querier/deployment-querier.yaml
> +            {{- toYaml .Values.tempo.readinessProbe | nindent 12 }}
```suggestion
          {{- with .Values.tempo.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
```

2023-08-01 11:38 UTC, zanhsieh approved these changes

2023-08-01 11:38 UTC, merged