Add support for PDB apiVersion to be specified
grafana/helm-charts pull request #2572
Opened 2023-08-02 11:32 UTC by titirigaiulian

Issue: https://github.com/grafana/helm-charts/issues/2571

2023-08-02 11:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2572) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2572) before we can accept your contribution.<br/><hr/>**Iulian Titiriga** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2572) it.</sub>

2023-08-23 11:16 UTC, titirigaiulian commented
> @titirigaiulian Thanks for the contribution. Can you bump version in Chart.yaml and sign DCO, so the CI can merge this PR once approved?

Thanks @zanhsieh, done

2023-08-23 12:17 UTC, Allex1 approved these changes

2023-08-24 07:37 UTC, zanhsieh requested changes

2023-08-24 07:37 UTC, zanhsieh commented on charts/grafana/values.yaml
> +#  apiVersion: {}
Should be string, not an object.
```suggestion
#  apiVersion: ""
```

2023-08-24 15:01 UTC, zanhsieh approved these changes

2023-08-24 15:02 UTC, merged