Add extraLabels entry
grafana/helm-charts pull request #2711
Opened 2023-10-16 15:36 UTC by matazr

2023-10-16 15:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2711) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2711) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2711) it.</sub>

2023-10-16 15:41 UTC, kvanzuijlen approved these changes
LGTM

2023-10-17 21:16 UTC, zanhsieh requested changes
@matazr 
Thanks for the contribution. Can you bump the version in Chart.yaml?

2023-10-18 09:20 UTC, matazr commented
atlantis unlock

2023-10-19 06:02 UTC, zanhsieh approved these changes

2023-10-19 06:03 UTC, merged