[grafana] Range over extraVolumes
grafana/helm-charts pull request #2712
Opened 2023-10-16 16:06 UTC by efbicief

Previously, this was ranging over extraVolumeClaims instead of extraVolumes, which meant extraVolumes was never read. This caused volumes mounted as extraVolumes to be mounted as emptyDirs.
This also correctly inserts all data from hostPath volumes, and allows configMaps to be used as an extraVolume.

This should fix https://github.com/prometheus-community/helm-charts/issues/3851

2023-10-16 16:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2712) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2712) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2712) it.</sub>

2023-10-18 15:15 UTC, zanhsieh requested changes
@efbicief 
Thanks for the contribution. Can you sign DCO and CLA please?

2023-10-24 10:46 UTC, efbicief commented
Apologies for the delay, hopefully that is okay now.

2023-10-24 10:48 UTC, efbicief commented
I see we are now on 6.61.1 - should version be bumped to 6.61.2?

2023-10-29 00:50 UTC, zanhsieh approved these changes

2023-10-29 00:50 UTC, merged