add externalTrafficPolicy support
grafana/helm-charts pull request #2716
Opened 2023-10-17 11:10 UTC by schneidermr

In some cases, the externalTrafficPolicy value should also be configured. The default value of externalTrafficPolicy is 'Cluster' which needs to change for example if you use an internal LoadBalancer type service in Microsoft Azure environment.

2023-10-17 11:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2716) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2716) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2716) it.</sub>

2023-10-17 21:09 UTC, zanhsieh requested changes
@schneidermr 
Thanks for the contribution. Can you bump the version in Chart.yaml please?

2023-10-18 14:55 UTC, schneidermr commented
> @schneidermr Thanks for the contribution. Can you bump the version in Chart.yaml please?

I bumped the version number of the Grafana chart

2023-10-18 16:39 UTC, zanhsieh approved these changes

2023-10-18 16:39 UTC, merged