use old root to get namespace
grafana/helm-charts pull request #2740
Opened 2023-10-26 07:45 UTC by kaflake

fix bug from #2723 which produces in #2679.

Namespace-Variable was nil and cause of that its not possible to build with basicauth.

2023-10-26 07:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2740) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2740) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2740) it.</sub>

2023-10-29 02:28 UTC, zanhsieh requested changes

2023-10-29 02:28 UTC, zanhsieh commented on charts/tempo-distributed/templates/gateway/secret-gateway.yaml
> +  namespace: {{ $root.Release.Namespace }}
```suggestion
  namespace: {{ $root.Release.Namespace | quote }}
```

2023-10-29 02:29 UTC, zanhsieh requested changes
@kaflake 
Can you bump the version in Chart.yaml and sign DCO please?

2023-11-23 14:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2740) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2740) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2740) it.</sub>

2023-11-23 14:23 UTC, kaflake commented
reopen with the new version. Sorry, I'm not working so often in github :/
Hoping this ist now working. Make the changes but do not request a new review.

2023-11-24 15:45 UTC, zanhsieh approved these changes

2023-12-05 08:17 UTC, kaflake reviewed
reviewed

2023-12-05 08:19 UTC, kaflake commented
What have I to do to finish this pull-request? Do I still a mistake?

2023-12-06 06:50 UTC, zanhsieh commented
> What have I to do to finish this pull-request? Do I still a mistake?

Ask other reviewers to see they have different opinions.

2023-12-15 19:31 UTC, rlex commented
can we please get it merged? I'm also affected and chart was unusable for me since 1.6.9. Of course i can pin to 1.6.9 and use image.tag but still.

2023-12-15 19:38 UTC, zalegrala approved these changes

2023-12-15 19:41 UTC, zalegrala commented
LGTM, the chart needs a version update.  Thanks for the contribution.

2023-12-16 21:17 UTC, merged