[loki-distributed] manage compactor as statefulset
grafana/helm-charts pull request #2747
Opened 2023-10-28 20:39 UTC by rasta-rocket

Hey there !

Small contribution here to allow users of the chart to manage the compactor as a statefulset

:warning: Also I draw you attention on the fact that in the `values.yaml` I set the compactor field `Kind` as `Statefulset` starting now : this might break existing setup. I did that since Statefulset is kind of the default way to manage stateful software in k8s IMHO, but let me know what you think about it :wink:

If you have any question, do not hesitate to reach me :wink:

Cheers :sunny:

2023-11-07 19:04 UTC, zanhsieh approved these changes

2023-11-09 07:05 UTC, zanhsieh commented
@zalegrala
Can you review this please?

2023-11-13 10:50 UTC, verejoel requested changes
This will introduce bugs if the compactor PVC is disabled which needs to be addressed, also please fix the copy-paste error.

2023-11-13 10:50 UTC, verejoel commented on charts/loki-distributed/templates/compactor/statefulset-compactor.yaml
> +        {{- if not .Values.ingester.persistence.enabled }}
Copy paste error
```suggestion
        {{- if not .Values.compactor.persistence.enabled }}
```

2023-11-13 10:50 UTC, verejoel commented on charts/loki-distributed/templates/compactor/statefulset-compactor.yaml
> +  volumeClaimTemplates:
Needs a guard here in case persistence is not enabled or the list of volume claims is empty.

2023-11-13 13:52 UTC, zalegrala commented
Thanks for the PR.  What's the motivation to manage the compactor as a statefulset?  Is this the recommendation from Loki?

2023-11-13 18:17 UTC, rasta-rocket commented
Hello @zalegrala 👋 

I did that for two reasons:
- Statefulset is kind of the default way to manage stateful software in k8s 
- When doing rolling update on deployment + pvc, the rolling is not well managed most of the time, because you need to detach the PV from the deployment N manually before deployment N+1 arrives (because you have concurrent access on the volume) : which result in a helm deployment that fails. That issue never occurs with an STS.

The recommendation from loki is to have that component to be stateful (they do not mention statefulset or deployment + pvc)

Cheers ☀️

2023-11-13 19:13 UTC, zalegrala approved these changes

2023-11-13 19:15 UTC, zalegrala commented
Ah okay, I didn't realize the compactor was stateful but I suppose this makes sense since if the client doesn't stream.

2023-12-20 09:06 UTC, merged