[grafana] allow sc-alerts as init container
grafana/helm-charts pull request #2761
Opened 2023-11-02 14:03 UTC by bt909

Sidecar for datasources and notifiers are available, but not for alerts.  As values.yaml in line 873 suggested, the idea is to have it as init container as well.

This PR enables the possibility to use sidecar-alerts as init-container too.

Why do we want this as init-container? To get alerts loaded, when using Grafana in anonymous mode. For datasources we have a solution, but not for alerts.

Some kind of related (but this PR don't fix it): https://github.com/grafana/helm-charts/issues/981

2023-11-03 10:18 UTC, bt909 commented
I have implemented as init-container OR container. If you like to have the init-container additional to the container, I can adjust that. In my usecase, I use Grafana w/ anonymous login and the container additional to init-container makes no sense in my usecase, but maybe to have both is the more generic way.

2023-11-07 13:20 UTC, zanhsieh requested changes
@bt909 
Can you fix the test error?

2023-11-07 13:20 UTC, zanhsieh commented on charts/grafana/README.md
> +| `sidecar.datasources.initAlerts`     | Set to true to deploy the datasource sidecar as an initContaine. This is needed if skipReload is true, to load any datasources defined at startup time. | `fal
```suggestion
| `sidecar.datasources.initAlerts` | Set to true to deploy the datasource sidecar as an initContainer. This is needed if skipReload is true, to load any datasources defined at startup time. | `false` |
```

2023-11-07 13:49 UTC, bt909 commented
Hm, I would like to fix the test, but I am a bit confused. The test failed since I merged main....

2023-11-07 14:15 UTC, bt909 commented
Oh, I am stuck in rebase hell, because of DCO. I will make an new clean PR.

2023-11-07 14:27 UTC, closed without merging

2023-11-07 14:27 UTC, bt909 commented
I will close this PR in favor of: https://github.com/grafana/helm-charts/pull/2771
Sorry for that.