Fixed broken URL to ALB actions in the README
grafana/helm-charts pull request #2773
Opened 2023-11-07 15:38 UTC by Mattie112

Since v2 it was renamed from "AWS ALB Ingress Controller" to  "AWS Load Balancer Controller"

2023-11-07 15:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2773) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2773) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2773) it.</sub>

2023-11-09 14:33 UTC, zanhsieh requested changes
@Mattie112 
Thanks for the contribution. Can you bump the version in Chart.yaml and sign DCO please?

2023-11-10 09:07 UTC, Mattie112 commented
> @Mattie112 Thanks for the contribution. Can you bump the version in Chart.yaml and sign DCO please?

It should be all good now!

2023-11-11 15:33 UTC, zanhsieh approved these changes

2023-11-14 09:19 UTC, Xtigyro approved these changes

2023-11-15 10:11 UTC, merged