[grafana] Document extraVolumes
grafana/helm-charts pull request #2823
Opened 2023-12-06 10:47 UTC by stephan2012

Update documentation for `extraVolumes`, introduced in https://github.com/grafana/helm-charts/commit/dbf7b82e21390d3a137d51898a1f1489f1eec8c2.

Resolves #2777

2023-12-06 10:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2823) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2823) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2823) it.</sub>

2023-12-06 14:23 UTC, zanhsieh approved these changes

2023-12-09 07:04 UTC, Xtigyro approved these changes

2023-12-11 10:28 UTC, stephan2012 commented
@Xtigyro The PR doesn't merge because GitHub thinks you haven't signed the CLA yet.

2023-12-11 13:40 UTC, Xtigyro requested changes
@stephan2012 Please bump the chart version.

2023-12-11 17:41 UTC, Xtigyro approved these changes

2023-12-12 14:34 UTC, merged