Support Datasource sidecar having envValueFrom
grafana/helm-charts pull request #2862
Opened 2023-12-20 11:13 UTC by mtenrero

This PR enables adding environment values from Secrets or ConfigMaps into the datasources sidecar, which is quite useful for registering datasources with ServiceAccount tokens, specially for OpenShift environments

2023-12-20 11:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2862) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2862) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2862) it.</sub>

2023-12-28 14:46 UTC, zanhsieh requested changes
@mtenrero 
Thanks for the contribution. Can you bump the version in Chart.yaml to latest and sign DCO please?

2024-01-12 02:39 UTC, zanhsieh approved these changes

2024-01-12 19:49 UTC, Xtigyro approved these changes

2024-01-12 19:50 UTC, merged