[loki-stack] updating for loki release 2.2.0
grafana/helm-charts pull request #290
Opened 2021-03-11 14:51 UTC by slim-bean

Signed-off-by: Edward Welch <edward.welch@grafana.com>

2021-03-11 15:04 UTC, owen-d approved these changes, later dismissed

2021-03-11 18:58 UTC, mkilchhofer approved these changes

2021-03-11 18:58 UTC, mkilchhofer commented on charts/loki-stack/values.yaml
> +    tag: 7.4.3
Is there a reason that we explicitly override the imageTag here? Why we don't us the subchart defaults?

2021-03-11 19:30 UTC, mkilchhofer requested changes

2021-03-11 19:30 UTC, mkilchhofer commented on charts/loki-stack/Chart.yaml
> +version: 2.4.0
I'd bump the major version since at least the promtail chart had a breaking change.

2021-03-16 20:06 UTC, christopher-wong commented
Hey there :wave: any update on when this might get fixed up and merged in?

2021-03-30 16:14 UTC, christopher-wong commented
@slim-bean any chance you could lend a hand here?

2021-04-06 10:04 UTC, patrickhuy commented
I hope you had enjoyable easter holidays! Any chance this could be moved forward? @slim-bean  @owen-d

2021-04-06 11:55 UTC, slim-bean commented
We just released 2.2.1 so I'm hoping to get back to this today and try to
figure out why it was failing tests.

On Tue, Apr 6, 2021 at 6:05 AM Patrick Huy ***@***.***> wrote:

> I hope you had enjoyable easter holidays! Any chance this could be moved
> forward? @slim-bean <https://github.com/slim-bean> @owen-d
> <https://github.com/owen-d>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/grafana/helm-charts/pull/290#issuecomment-813997673>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACO2RK4NTJXCYC6347SLHZDTHLMFFANCNFSM4ZANQTTQ>
> .
>

2021-04-16 20:06 UTC, coultenholt commented
We are also waiting on this change to go through as well. Any update @slim-bean ?

2021-06-08 15:45 UTC, coultenholt commented
@slim-bean 
What is blocking this PR from being merged? Anything I can help with?

2021-06-24 14:36 UTC, mcpappas commented
I just tried to use the loki-stack chart and was confused why promtail wasn't parsing the logs correctly. Several hours of wading through old commits and kubernetes/docker/containerd documentation I've found that this has bitten me too. The simple fact that loki-stack is using a promtail so far behind main is very confusing. If I can find the time, I may submit my own PR to see if we can't get this pushed through to prevent anyone else like me burning time on this.

2021-06-24 14:43 UTC, onedr0p commented
It's been more than a couple months @slim-bean Please provide an update ❤️

2021-07-05 11:46 UTC, lucaim commented
Hi @slim-bean, it looks to me that the tests are not passing because the promtail chart assumes that it is `loki-gateway` is present (https://github.com/grafana/helm-charts/blob/0a2deec6784b58e06a6794593652ba62e1c706bf/charts/promtail/values.yaml#L235) instead of being just `loki` as a service. 
I suppose that this is missing in the helm chart compared to the Jsonnet version (https://github.com/grafana/loki/blob/main/production/ksonnet/loki/gateway.libsonnet)

2022-06-15 18:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=290) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=290) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=290) it.</sub>

2022-06-16 00:02 UTC, closed without merging