Don't fail assertNoLeakedSecrets check if a variable expansion operator is found
grafana/helm-charts pull request #2904
Opened 2024-01-14 23:23 UTC by bdalpe

Checks for the presence of the following syntax anywhere in the setting (based on the documentation here: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#variable-expansion):

`${whatever}` or `$__<provider>{whatever}`

If these are found, validation passes.

Fixes #2899

2024-01-15 11:12 UTC, zanhsieh approved these changes

2024-01-16 07:45 UTC, Xtigyro approved these changes

2024-01-16 14:29 UTC, z0rc requested changes

2024-01-16 14:29 UTC, z0rc commented on charts/grafana/templates/_helpers.tpl
> +              {{- if not (regexMatch "\\$(?:__(?:env|file|value))?{[^}]+}" (index $currentMap $elem)) -}}
```suggestion
              {{- if not (regexMatch "\\$(?:__(?:env|file|vault))?{[^}]+}" (index $currentMap $elem)) -}}
```

2024-01-16 14:54 UTC, bdalpe commented on charts/grafana/templates/_helpers.tpl
> +              {{- if not (regexMatch "\\$(?:__(?:env|file|value))?{[^}]+}" (index $currentMap $elem)) -}}
Good catch @z0rc. I'll fix that.

2024-01-16 15:23 UTC, bdalpe commented on charts/grafana/templates/_helpers.tpl
> +                {{- fail (printf "Sensitive key '%s' should not be defined explicitly in values. Use variable expansion instead." (join "." $secret.path)) -}}
Added help message in f5a1c08.

2024-01-16 19:36 UTC, bdalpe commented on charts/grafana/templates/_helpers.tpl
> +              {{- if not (regexMatch "\\$(?:__(?:env|file|vault))?{[^}]+}" (index $currentMap $elem)) -}}
There's a trade off between forcing compliance with a strict match and the inverse of making the Helm Chart easy to use. Requiring strict validating will cause values like `${env}-something` to be considered invalid, while they are perfectly legitimate for use. This validation is more of a sanity check. FWIW, I didn't write the original validation, just writing a fix for those that want to use configuration in `grafana.ini` and not as environment variables.

Considering that two approvers have already signed off, I'm not planning on changing this.

2024-01-16 19:37 UTC, bdalpe commented
@Xtigyro or @zanhsieh, can you re-approve the workflows?

2024-01-16 21:26 UTC, bdalpe commented on charts/grafana/templates/_helpers.tpl
> +              {{- if not (regexMatch "\\$(?:__(?:env|file|vault))?{[^}]+}" (index $currentMap $elem)) -}}
Because `$__<invalid>{...}` is ignored by the variable expander and treated as a literal value.

2024-01-18 09:23 UTC, stefanandres commented
Thanks for the PR! Came here to tell this. All our grafana helm releases with okta are basically broken now because of
```
grafana/templates/deployment.yaml:36:28): Sensitive key 'auth.okta.client_secret' should not be defined explicitly in values. Use variable expansion instead
```

Even though we already use
```
client_secret: $__file{/etc/secrets/auth_okta/client_secret}
```

2024-01-18 09:57 UTC, zanhsieh approved these changes

2024-01-18 16:03 UTC, bdalpe commented
Will need someone with write access to merge as I don't have permissions.

2024-01-19 03:15 UTC, merged

2024-01-22 12:34 UTC, P-n-I commented
lgtm, thanks!