bump appVersion
grafana/helm-charts pull request #2915
Opened 2024-01-18 11:17 UTC by vainikkaj

2024-01-18 11:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2915) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2915) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2915) it.</sub>

2024-01-18 13:17 UTC, zanhsieh requested changes

2024-01-18 13:17 UTC, zanhsieh commented on charts/tempo/Chart.yaml
>  version: 1.7.1
`version` should be bumped too.

```suggestion
version: 1.7.2
```

2024-01-18 22:29 UTC, zanhsieh approved these changes

2024-07-30 08:17 UTC, zanhsieh commented
@Sheikh-Abubaker Can you review this PR please?

2024-07-30 19:41 UTC, Sheikh-Abubaker reviewed
@zanhsieh I'm not being able to understand the scope of this PR, the tempo chart version is already at it's latest [version](https://artifacthub.io/packages/helm/grafana/tempo)

2024-07-31 08:52 UTC, closed without merging