feat: adds multi-org support to sidecar dashboards
grafana/helm-charts pull request #2939
Opened 2024-01-26 13:26 UTC by mango-matt

converts `sidecar.dashboards.provider` to a list at
`sidecar.dashboards.providers` allowing the definition of multiple
providers that can be mappped to orgs as required.

still supports the singular variant to retain backwards compatibility
and will prepend it to any configured `providers`

Results in multi-org support defining providers like the example below which 

```
sidecar:
    dashboards:
      enabled: true
      providers:
        - name: prod
          orgid: 1
        - name: nonprod
          orgid: 2
        - name: ops
          orgid: 3
```

This then allows dashboard configmaps to be define the annotation `k8s-sidecar-target-directory: /tmp/dashboards/ops` instructing the sidecar to put the dashboard in the folder that's been specific in our configuration above.

2024-01-26 13:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2939) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2939) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2939) it.</sub>

2024-01-29 12:01 UTC, zanhsieh approved these changes

2024-02-02 22:45 UTC, zanhsieh requested changes

2024-02-02 22:45 UTC, zanhsieh commented on charts/grafana/Chart.yaml
>  version: 7.3.0
```suggestion
version: 7.4.0
```

2024-02-06 10:18 UTC, mango-matt commented
closing as have been made aware that multi-org features are not being pursued

2024-02-06 10:18 UTC, closed without merging