[grafana] conf(grafana): Add `folderUid` option
grafana/helm-charts pull request #2956
Opened 2024-02-07 14:52 UTC by Rohlik

My first PR 🎉 !
This simple PR should allow users to be able to set a `folderUid` which may help solve issues in some deployments, see referencing ticket for more info.

TICKET: Fix #2955

2024-02-07 14:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=2956) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=2956) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=2956) it.</sub>

2024-02-08 23:01 UTC, zanhsieh requested changes
@Rohlik 
Can you bump the version in Chart.yaml and sign DCO please?

2024-02-09 09:01 UTC, Rohlik commented
@zanhsieh Thx for the review.
DCO is already signed.
Bumping `Chart.yaml` now.

2024-02-10 01:06 UTC, zanhsieh requested changes

2024-02-10 01:06 UTC, zanhsieh commented on charts/grafana/Chart.yaml
> +version: 7.3.1
```suggestion
version: 7.4.0
```

2024-02-15 16:24 UTC, zanhsieh approved these changes

2024-05-15 07:54 UTC, Rohlik commented
@zanhsieh Hey 👋🏼, can we merge this? I do not want to do a rebase again and again 🙄.

2024-05-27 00:54 UTC, zanhsieh commented
> @zanhsieh Hey 👋🏼, can we merge this? I do not want to do a rebase again and again 🙄.
@Rohlik 
I can't. It required two approvals. I don't control this grafana repo, grafana.com does. Long long time ago only requires single approval but they change the policy somehow.

2024-06-03 15:27 UTC, zalegrala approved these changes

2024-06-04 14:39 UTC, zalegrala approved these changes

2024-06-04 17:41 UTC, Rohlik commented
Just you @zanhsieh and we are ready to go 🚀.

2024-06-07 20:56 UTC, merged

2024-06-07 20:56 UTC, zalegrala commented
Thanks for the contribution @Rohlik.