DOCS fix tempo-distributed
grafana/helm-charts pull request #3027
Opened 2024-03-15 17:15 UTC by mattclegg

Update TYPOs in DOCS

2024-04-12 07:41 UTC, krajorama requested changes
Hi @mattclegg,

please review the https://github.com/mattclegg/grafana--helm-charts/blob/DOCS-fix-tempo-distributed/CONTRIBUTING.md guideline. Signing commits is required and also a version bump (on patch level in this case, e.g. 1.9.1->1.9.2), which in turn implies running helm-docs to update the README of the chart.

It's not stated there, but the automation will also refuse PRs that change more than one chart, so I'd advise to move the changes to the tempo chart from #2791 here in this PR.

regards, krajo
please direct mention me (@krajorama ) in reply, otherwise I can miss notifications - I get a tonne

2024-05-14 15:26 UTC, mattclegg commented
Ok @krajorama 

Rebased/signed & cherry-picked relevant changes to this PR.

2024-06-11 11:30 UTC, mattclegg commented
Merged upstream (again) @krajorama

2024-07-31 17:13 UTC, Sheikh-Abubaker reviewed
Thanks for the contribution! @mattclegg, could you please address the CI lint errors ?

2024-08-06 16:35 UTC, Sheikh-Abubaker reviewed
@mattclegg could you please address failed checks ?

2025-10-31 21:49 UTC, Sheikh-Abubaker commented
Hey @mattclegg I wonder if you're still open to working in this PR ?

2025-11-20 15:30 UTC, mattclegg commented
@Sheikh-Abubaker rebased (again)

2025-11-20 18:28 UTC, knylander-grafana submitted a review, later dismissed
Thank you for fixing the typos in the docs.

2026-05-21 17:33 UTC, Sheikh-Abubaker commented
@mattclegg Thanks for your contribution if you're interested you could open this PR in the community [repo](https://github.com/grafana-community/helm-charts), as this chart is no longer maintained here

2026-05-21 17:34 UTC, closed without merging