Fix HPA selector for `grafana helm charts`
grafana/helm-charts pull request #3050
Opened 2024-03-31 14:34 UTC by gritzkoo

Previous PR try: <https://github.com/grafana/helm-charts/pull/3033>

related issues:

- #2558 
- #2493
- #2126 
- #1391 

Fix the helper to select the correct HPA on kubernetes >=v1.23.

This new select has tested in my local kubernetes development and the right version has selected!

![image](https://github.com/grafana/helm-charts/assets/10054367/0d777dea-6613-4b7e-9e45-58e324920f77)
![image](https://github.com/grafana/helm-charts/assets/10054367/7b0ec6f7-8b07-46f0-ada5-b811403eef3f)
![image](https://github.com/grafana/helm-charts/assets/10054367/afdfb9ee-6734-4cdf-9c64-cf47dd75f152)
[grafana-6.57.0.tgz](https://github.com/grafana/helm-charts/files/14649138/grafana-6.57.0.tgz)

___

I tested on version 6.57.0 in my local but the issue is the same on the latest version.

2024-03-31 14:49 UTC, zanhsieh requested changes

2024-03-31 14:49 UTC, zanhsieh commented on charts/grafana/templates/_helpers.tpl
> +  {{- end }}
```suggestion
{{- if .Capabilities.APIVersions.Has "autoscaling/v2" }}
{{- print "autoscaling/v2" }}
{{- else }}
{{- print "autoscaling/v2beta2" }}
{{- end }}
```

2024-04-15 07:45 UTC, zanhsieh approved these changes

2024-05-01 13:02 UTC, zanhsieh commented
@Xtigyro @zalegrala Can you approve this PR plz?

2024-05-02 15:59 UTC, zalegrala approved these changes

2024-05-07 22:49 UTC, merged