chore: set unique cluster_label for loki-distributed memberlist
grafana/helm-charts pull request #3057
Opened 2024-04-03 15:32 UTC by hobbsh

Addressing https://github.com/grafana/tempo/issues/2766 where Loki/Tempo ingesters can join each other's ring because cluster_label seems to be defaulted to something common to both components. This change should mitigate the issue in the future.

2024-05-10 06:49 UTC, zanhsieh approved these changes

2024-11-06 20:24 UTC, Sheikh-Abubaker commented on charts/loki-distributed/Chart.yaml
> +version: 0.79.1
```suggestion
version: 0.80.0
```

2024-11-06 20:26 UTC, Sheikh-Abubaker requested changes
Hey @hobbsh could you please bump the minor version ?

2024-11-06 20:28 UTC, Sheikh-Abubaker requested changes
```suggestion
version: 0.80.0
```

2024-11-06 20:28 UTC, Sheikh-Abubaker commented on charts/loki-distributed/Chart.yaml
> +version: 0.79.1
```suggestion
version: 0.80.0
```

2024-11-06 22:12 UTC, hobbsh commented
@Sheikh-Abubaker done, thank you

2024-11-14 23:49 UTC, Sheikh-Abubaker commented
@hobbsh could you please sign the DCO, thanks!

2024-11-15 00:31 UTC, hobbsh commented
@Sheikh-Abubaker Done

2024-11-15 00:46 UTC, Sheikh-Abubaker commented on charts/loki-distributed/README.md
> +Introduces a default `cluster_label` for the ring memberlist, which will temporarily disrupt ingestion as it rolls out, unless you temporarily set `cluster_label_verification_disabled`.
could you we have a more descriptive note like: https://github.com/grafana/helm-charts/pull/3058/files#diff-692d159d251d994ada48f63a9a8d8d570ff515aec9a09c1d156544e786d3efa6R42-R45 ?

2024-11-15 00:48 UTC, Sheikh-Abubaker commented on charts/loki-distributed/README.md.gotmpl
> +Introduces a default `cluster_label` for the ring memberlist, which will temporarily disrupt ingestion as it rolls out, unless you temporarily set `cluster_label_verification_disabled`.
could you we have a more descriptive note like: https://github.com/grafana/helm-charts/pull/3058/files#diff-692d159d251d994ada48f63a9a8d8d570ff515aec9a09c1d156544e786d3efa6R44-R45 ?

2024-11-15 00:50 UTC, Sheikh-Abubaker reviewed
Looks good! left some comments on readme, do check it out!

2024-11-15 16:34 UTC, hobbsh commented
@Sheikh-Abubaker Done

2024-11-15 17:47 UTC, Sheikh-Abubaker approved these changes
LGTM! Thanks for your contribution, keep them coming!

2024-11-15 18:41 UTC, merged