Fixes annotations JSON to YAML for service-monitor
grafana/helm-charts pull request #3181
Opened 2024-06-19 09:30 UTC by KateFiroozi

2024-06-19 09:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=3181) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=3181) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=3181) it.</sub>

2024-06-21 13:39 UTC, ein-stein-chen requested changes

2024-06-21 13:39 UTC, ein-stein-chen commented on charts/promtail/templates/service-metrics.yaml
> +  {{- end }}
The additional labels should probably also be inside an `{{- if …}}`, or?

```suggestion
  labels:
    {{- include "promtail.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
```

2024-07-06 15:23 UTC, Sheikh-Abubaker commented
Closing this on behalf of #3164

2024-07-06 15:24 UTC, closed without merging

2024-07-06 15:24 UTC, Sheikh-Abubaker commented
Closing this on behalf of #3164

2024-07-09 10:23 UTC, Sheikh-Abubaker reviewed
Closed this on behalf of #3164