[tempo-distributed]: Fix zone aware replication upgrade and rollout operator
grafana/helm-charts pull request #3189
Opened 2024-06-26 11:07 UTC by KyriosGN0

@z0rc, please test upgrade againts this PR, i forgot to add an else clause that adds the default zone if zone aware replication is set to false (weird it only happens during an upgrade

2024-06-26 11:31 UTC, z0rc commented
@KyriosGN0 sure I can test the upgrade path, but first regular checks must pass. I tried to verify upgrade now and got relatively same error as in lint-test check:
```
Error: unable to generate manifests: cannot patch "tempo-ingester" with kind StatefulSet:  "" is invalid: patch: Invalid value:
... 
json: cannot unmarshal string into Go struct field PodSpec.spec.template.spec.affinity of type v1.Affinity
```

2024-06-26 11:57 UTC, KyriosGN0 commented
@z0rc fixed the tests issue

2024-06-26 12:10 UTC, z0rc requested changes
Upgrade from 1.12.0 works on my end, regular ingester statefulset remains in place.

Minor comments, otherwise LGTM.

2024-06-26 12:10 UTC, z0rc commented on charts/tempo-distributed/values.yaml
```suggestion
# -- Enable rollout-operator. It must be enabled when using Zone Aware Replication.
rollout_operator:
  enabled: false
  
```

2024-06-26 12:10 UTC, z0rc commented on charts/tempo-distributed/README.md
> +| rollout_operator.enabled | bool | `false` |  |
Please regenarate docs after adding description to variable.

2024-06-26 12:10 UTC, z0rc commented on charts/tempo-distributed/README.md.gotmpl
> +### from Chart versions < 1.12.0
"Less than" sign is confusing here. AFAIU with recent changes it should be 
```suggestion
### from Chart versions < 1.13.1
```
Or 1.13.0 IDK.

2024-06-26 12:11 UTC, z0rc commented on charts/tempo-distributed/values.yaml
> +  enabled: false
```suggestion
# -- Enable rollout-operator. It must be enabled when using Zone Aware Replication.
rollout_operator:
  enabled: false
  
```

2024-06-26 12:37 UTC, KyriosGN0 commented
fixed! @z0rc thank you so much!

2024-06-26 13:05 UTC, KyriosGN0 commented on charts/tempo-distributed/values.yaml
> +  enabled: false
fixed!

2024-06-26 13:37 UTC, z0rc approved these changes

2024-06-26 17:13 UTC, KyriosGN0 commented
@maorfr @faustodavid @swartz-k @BitProcessor 
Sorry for the ping, can anyone take a look to see if all is good?

2024-06-27 13:04 UTC, MikaelElkiaer commented
I wonder if this is related to an issue I am seeing.

I upgraded from `1.12.0` to `1.13.0` and all my ingesters disappeared.
I had to roll back to `1.12.0` to restore my them.

<details><summary>My values are:</summary>
<p>

```yaml
gateway:
  enabled: true
global_overrides:
  defaults:
    metrics_generator:
      processors:
        - service-graphs
        - span-metrics
memberlist:
  # INFO: See https://github.com/grafana/loki/issues/10172#issuecomment-1763475167
  cluster_label: tempo
  join_members:
    - dns+{{ include "tempo.fullname" . }}-gossip-ring.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:{{ .Values.memberlist.bind_port }}
metaMonitoring:
  serviceMonitor:
    enabled: true
    labels:
      release: prom-stack
metricsGenerator:
  enabled: true
traces:
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true
distributor:
  config:
    log_received_spans:
      enabled: true
```

</p>
</details>

2024-06-27 13:47 UTC, KyriosGN0 commented
@MikaelElkiaer is it exactly that. this PR aims to solve this issue

2024-06-28 11:05 UTC, KyriosGN0 commented
@mapno @faustodavid @BitProcessor @swartz-k again sorry for the ping but I would like to get this merged asap

2024-07-01 07:42 UTC, mapno approved these changes
Thanks for the fix

2024-07-02 11:19 UTC, KyriosGN0 commented
@faustodavid @swartz-k @BitProcessor, missing one more approve in order to fix this 
is there something i could to to help with the review ?

2024-07-02 11:21 UTC, faustodavid approved these changes
Thanks for your contribution!

2024-07-02 11:22 UTC, faustodavid commented
Can you please update the branch?

2024-07-02 11:39 UTC, KyriosGN0 commented
@faustodavid thank you very much. updated branch

2024-07-02 11:41 UTC, merged