[tempo-distributed] bump rollout-operator and grafana-agent-operator deps to latest
grafana/helm-charts pull request #3204
Opened 2024-07-03 01:59 UTC by DrFaust92

2024-07-03 01:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=3204) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=3204) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=3204) it.</sub>

2024-07-04 17:50 UTC, Sheikh-Abubaker requested changes

2024-07-04 17:50 UTC, Sheikh-Abubaker commented on charts/tempo-distributed/Chart.yaml
> +version: 1.13.3
Chart version should bump minor version
```suggestion
version: 1.14.0
```

2024-07-06 11:19 UTC, Sheikh-Abubaker commented
@DrFaust92 could you fix the CI lint please.

2024-07-06 11:54 UTC, Sheikh-Abubaker approved these changes

2024-07-06 11:54 UTC, Sheikh-Abubaker commented
LGTM!

2024-07-06 11:57 UTC, zanhsieh approved these changes

2024-07-06 11:58 UTC, merged