fix: force loki-distributed nginx gateway to resolve upstream hostname on missing locations
grafana/helm-charts pull request #3206
Opened 2024-07-03 15:29 UTC by rsicart

In order to force nginx to resolve hostnames in proxy_pass directive, we
need to set a variable and use it in proxy_pass. Otherswise nginx only
resolves hostnames at boot time.

2024-07-25 15:27 UTC, rsicart commented
> Hey there @rsicart, thanks for the contribution, Have you tested it ?

helm template works correctly.

Installing the chart locally in a [kind](https://kind.sigs.k8s.io/) cluster works fine, gateway is _Running_ and nginx config syntax is ok:

```
~/repos/github.com/rsicart/grafana-helm-charts/charts/loki-distributed k8s:kind-kind:: ~ git:rsi/loki-distributed-force-nginx-resolve-dns-proxy-pass » helm upgrade --install loki-distributed . --set gateway.nginxConfig.resolver=10.96.0.10
....

~/repos/github.com/rsicart/grafana-helm-charts/charts/loki-distributed k8s:kind-kind:: ~ git:rsi/loki-distributed-force-nginx-resolve-dns-proxy-pass » kubectl get pods                                                                       
NAME                                              READY   STATUS    RESTARTS   AGE
loki-distributed-distributor-5f98995f99-tjthf     1/1     Running   0          10m
loki-distributed-gateway-74c6945df-47j97          1/1     Running   0          6m
loki-distributed-ingester-0                       1/1     Running   0          10m
loki-distributed-querier-0                        1/1     Running   0          10m
loki-distributed-query-frontend-cbf67c5df-8tgb4   1/1     Running   0          10m

~/repos/github.com/rsicart/grafana-helm-charts/charts/loki-distributed k8s:kind-kind:: ~ git:rsi/loki-distributed-force-nginx-resolve-dns-proxy-pass » kubectl exec -ti loki-distributed-gateway-74c6945df-47j97 -- nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

2024-08-10 04:43 UTC, zanhsieh requested changes

2024-08-10 04:43 UTC, zanhsieh commented on charts/loki-distributed/README.md
> +| compactor.persistence.claims | list |  | List of the compactor PVCs |
Please do not change this value directly since it's generated by helm-docs.

2024-08-10 04:43 UTC, zanhsieh commented on charts/loki-distributed/README.md
> +| ingester.persistence.claims | list |  | List of the ingester PVCs |
same as above.

2024-08-11 12:12 UTC, Sheikh-Abubaker reviewed
@rsicart Could you please address the requested changes and fix CI lint error ? Thank you!

2024-08-12 10:21 UTC, zanhsieh approved these changes

2024-08-12 11:40 UTC, Sheikh-Abubaker approved these changes

2024-08-12 12:03 UTC, merged