Tempo-distributed: Service type and internalTrafficPolicy settings to Ingress/Distributor
grafana/helm-charts pull request #3361
Opened 2024-10-15 06:37 UTC by kovaxur

Added the following features to the helm chart of tempo-distributed:

- users can set service type on the ingester service
- users can set internalTrafficPolicy on both ingester/distributor services

2024-10-15 13:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=3361) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=3361) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: kovaxur<br/>:x: directedDevops<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=3361) it.</sub>

2024-11-12 07:21 UTC, kovaxur commented
Hey @Sheikh-Abubaker, can you please approve the workflows?

2024-11-14 13:43 UTC, zalegrala approved these changes

2024-11-14 18:29 UTC, Sheikh-Abubaker requested changes

2024-11-14 18:29 UTC, Sheikh-Abubaker commented on charts/tempo-distributed/Chart.yaml
> +version: 1.21.2
```suggestion
version: 1.22.0
```

2024-11-14 23:24 UTC, Sheikh-Abubaker commented on charts/tempo-distributed/README.md
> +![Version: 1.21.2](https://img.shields.io/badge/Version-1.21.2-informational?style=flat-square) ![Type: application](https://img.shields.io/badge/Type-application-informational?style=flat-square) ![A
```suggestion
![Version: 1.22.0](https://img.shields.io/badge/Version-1.22.0-informational?style=flat-square) ![Type: application](https://img.shields.io/badge/Type-application-informational?style=flat-square) ![AppVersion: 2.6.0](https://img.shields.io/badge/AppVersion-2.6.0-informational?style=flat-square)
```

2024-11-14 23:42 UTC, Sheikh-Abubaker approved these changes

2024-11-14 23:43 UTC, merged