[grafana] FIX: yaml indentation in README.md
grafana/helm-charts pull request #3382
Opened 2024-10-29 10:52 UTC by b-o-g-d-a-n

2024-10-29 10:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=3382) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=3382) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=3382) it.</sub>

2024-10-29 11:03 UTC, jkroepke requested changes
Please bump the chart version, thanks!

2024-10-29 14:25 UTC, jkroepke approved these changes

2024-10-29 18:27 UTC, Sheikh-Abubaker commented
@b-o-g-d-a-n  could you please update the branch ?

2024-10-30 11:43 UTC, zanhsieh approved these changes

2024-10-30 15:59 UTC, merged