Update tempo-vulture to 2.6.1
grafana/helm-charts pull request #3412
Opened 2024-11-08 19:39 UTC by farcaller

Split from #3404

2024-11-08 19:52 UTC, Sheikh-Abubaker requested changes

2024-11-08 19:52 UTC, Sheikh-Abubaker commented on charts/tempo-vulture/Chart.yaml
> +version: 0.7.0
```suggestion
version: 0.7.1
```

2024-11-08 19:52 UTC, Sheikh-Abubaker commented on charts/tempo-vulture/README.md
> +![Version: 0.7.0](https://img.shields.io/badge/Version-0.7.0-informational?style=flat-square) ![Type: application](https://img.shields.io/badge/Type-application-informational?style=flat-square) ![App
```suggestion
![Version: 0.7.1](https://img.shields.io/badge/Version-0.7.1-informational?style=flat-square) ![Type: application](https://img.shields.io/badge/Type-application-informational?style=flat-square) ![AppVersion: 2.6.1](https://img.shields.io/badge/AppVersion-2.6.1-informational?style=flat-square)
```

2024-11-09 21:41 UTC, Sheikh-Abubaker approved these changes

2024-11-09 23:37 UTC, zanhsieh approved these changes

2024-11-09 23:37 UTC, merged