[tempo] Add servicemonitor namespace and values note
grafana/helm-charts pull request #3506
Opened 2024-12-31 10:09 UTC by daviderli614

The ServiceMonitor does not have a namespace specified, need to define namespace.
Add value comments and document link can help users configure better.

2024-12-31 10:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=3506) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=3506) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=3506) it.</sub>

2025-01-12 18:29 UTC, Sheikh-Abubaker requested changes

2025-01-12 18:29 UTC, Sheikh-Abubaker commented on charts/tempo/values.yaml
> +  # -- Configuration options for the server.
```suggestion
  # Tempo server configuration.
```

2025-01-12 19:49 UTC, daviderli614 commented
Hi @Sheikh-Abubaker 
I have modified according to the suggestion.

2025-01-15 19:12 UTC, Sheikh-Abubaker approved these changes

2025-01-15 21:12 UTC, joe-elliott approved these changes

2025-01-18 15:22 UTC, merged