[loki-rule-operator] add new chart to install loki rules crds
grafana/helm-charts pull request #377
Opened 2021-04-12 19:26 UTC by nvanheuverzwijn

This PR introduces a new helm-chart that add CRDs to manage loki rules.

I beleive it resolves these two issues :
https://github.com/grafana/loki/issues/2990
https://github.com/grafana/loki/issues/3456

See https://github.com/opsgy/loki-rule-operator for source code

2021-05-13 16:31 UTC, unguiculus requested changes
I don't think this repo should host charts for non-Grafana apps. Please host that chart in your own repo.

2021-05-26 15:19 UTC, nvanheuverzwijn commented
@unguiculus Well, if grafana people wants to take over the source code, I'm pretty sure the author wouldn't mind. However, if Grafana does not care, well, I don't care either. This is a requested feature for a part of the community so it makes sense to have it here or at least, have a reference somewhere if it's only in this PR.

It wouldn't be the first time Grafana would use thrid party code. They do use kiwigrid side-car containers which is not from Grafana team itself.

2022-06-15 18:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=377) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=377) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=377) it.</sub>

2022-06-28 16:30 UTC, closed without merging

2025-06-19 19:15 UTC, sharovmerk commented
@trevorwhitney can it be integrated to Grafana then?