Add loki charts
grafana/helm-charts pull request #39
Opened 2020-10-03 21:53 UTC by torstenwalter

This adds the charts from the [loki](https://github.com/grafana/loki) repository (fluent-bit, loki, loki-stack and promtail) to this repo.

It includes the existing history. You can verify it yourself by checking the history for individual files as in the example:

```console
$ git log --oneline charts/loki/Chart.yaml
47ae03c7 bump chart versions and align READMEs
6c3d8033 Add support for PV selector in Loki statefulset (#2554)
03b944e6 updating images to 1.6.0 (#2504)
da9a22dc Add projected and downwardAPI volume types to PodSecurityPolicy (#2355) (#2366)
ca6f2e0d helm: add annotations to service monitor (#2258)
2379cab3 helm: Add loadBalancerIP option to loki chart (#2238)
d837f94d BUG: add missing namespace in ingress object (#2205)
e864f1e4 updating all the images to 1.5.0 release (#2100)
c042b22e helm chart: add missing line feed (#1967)
2f22bdb2 Reverting helm changes which were included in Cortex 1.0 vendor upgrade because it resulted in us pushing an unstable helm.
dfc0778d bumps helm to keepalive-master after cortex vendoring (#1937)
79234cb1 updating helm and ksonnet to 1.4.1 updating Fluent Bit to correct image
b53037c7 updating helm and ksonnet for 1.4.0 release
4b496db7 Move default port for Loki to 3100 everywhere. (#1838)
2d22ae09 Prevent prometheus to scrap both services (#1817)
b2c1287c Added support for imagePullSecrets in Loki Helm chart (#1632)
0b5c3de9 [loki helm chart] added ingress (#1585)
2faa3775 helm: Allow setting 'loadBalancerSourceRanges' for the loki service (#1553)
43ca2e13 updating to 1.3.0 release
d367078a helm: support adding init containers to the loki pod (#1336)
53c4f6cb v1.2.0: update helm and ksonnet (#1389)
3563f1c0 Updating version numbers for 1.1.0 release
fa5e81d4 Update loki helm chart to support service account annotations (#1341)
7a639abf updating helm and ksonnet to version v1.0.0 (#1292)
1b9171d9 helm: update default terminationGracePeriodSeconds to 4800 (#1257)
727fdee8 Helm path update (#1061)
c776952f update versions to new release
92f3a942 Helm: Fix the reference error of loki/loki helm chart (#1056)
7173bcd2 helm: Add support for passing arbitrary secrets (#1111)
7fe67cfe Feature: Add extra containers to loki helm chart (#909)
fce1d990 Helm: Remove default value of storageClassName in loki/loki helm chart (#1058)
6e47577f Bump chart versions
b40eb435 bump chart
4fca8ec6 update  helm and ksonnet to 0.3.0
61c077fe release: update ksonnet and helm charts to version v0.2.0
5a9c666c Helm chart: Added service monitor (#824)
424f36ed Helm: Be able to customize the Namespace (#830)
81c54b79 updating versions for loki v0.1.0
264884a5 fix labels for PodDisruptionBudget on helm (#623)
d5e22518 Limits: Reject entries based on age set in limits (#631)
5db6cfd4 Switch Loki to StatefulSet (#585)
8c0383d2 Helm chart tracing variable fix (#621)
d535827f ksonnet changes for running loki in single binary (#622)
481929f6 Added namespace to helm install notes (#617)
19c4d3f4 need to bump helm chart after PR #598
1b0d55be Limiting query start time with config (#572)
09d633b0 add optional PodDisruptionBudget to helm chart (#515)
f56cb644 Add option (#528)
d8c0feb0 Enable tracing loki in helm chart (#496)
2229932b Helm: Allow custom loki config
e5ed45af Separate loki & promtail charts
513388ad Setup Helm chart repository
```

These are the command, which have been used to migrate the history:

```console
# Prepare loki repository for merge
git clone git@github.com:grafana/loki.git /tmp/loki
cd /tmp/loki
# Filter history for helm charts to reduce repository size
git filter-repo --path-glob 'production/helm/*' --path-rename production/helm/:charts/

# Merge history into helm-charts repository
git clone git@github.com:grafana/helm-charts.git /tmp/grafana-helm-charts
cd /tmp/grafana-helm-charts
git checkout -b merge-loki-charts
git remote add -f loki /tmp/loki/.git
git merge --allow-unrelated-histories -s ours --no-commit loki/master
git read-tree --prefix=charts/fluent-bit -u loki/master:charts/fluent-bit
git read-tree --prefix=charts/loki -u loki/master:charts/loki/
git read-tree --prefix=charts/loki-stack -u loki/master:charts/loki-stack/
git read-tree --prefix=charts/promtail -u loki/master:charts/promtail
git commit -s -S -m "Added fluent-bit, loki, loki-stack and promtail charts"
```

Filtering the history was did a great trick on reducing the history size. 

In addition to migrating the repositories the following things have been done:

- all linting errors in Markdown files have been resolved
- minor version of all charts have been increased
  The goal of this is to publish a newer version of the charts from this repo. I choose to increase the minor version so that it's possible to increase the patch version to deprecate the existing charts and point to the new location.
- all READMEs have been adjusted to take the new helm repository location into account.

Part-of: grafana/loki#2593

2020-10-04 04:16 UTC, zanhsieh commented
Agreed. @torstenwalter 👍

2020-10-05 17:10 UTC, scottrigby requested changes
Just a few comments, otherwise everything looks great 👍 Nicely done!

2020-10-05 17:10 UTC, scottrigby commented on charts/loki-stack/requirements.yaml
> +  repository:  "https://kubernetes-charts.storage.googleapis.com/"
There is a logstash chart in the elastic charts repo https://github.com/elastic/helm-charts#charts, but the stable chart hasn't officially deprecated in it's favor yet. You might want to make an issue here to track that (part of that issue would also be cleaning up the stable URL from `chart-repos` in `ct.yaml`.

Any help with getting the rest of these elastic charts officially deprecated in stable would be appreciated.

2020-10-05 17:10 UTC, scottrigby commented on ct.yaml
> +  - stable=https://kubernetes-charts.storage.googleapis.com/
See logstash comment above.

2020-10-05 17:57 UTC, torstenwalter commented on charts/loki-stack/requirements.yaml
> +  repository: "file://../loki"
I would prefer to do this in a follow up PR. Like this it would fail at the moment as released charts are not migrated to gh-pages branch so far.

2020-10-12 12:43 UTC, owen-d commented
Thanks for the writeup; this looks great. I think it's reasonable to have a followup PR to change the repository references as you've suggested @torstenwalter. This also seems sensible for @scottrigby's logstash comments.

Anything else y'all see that needs to be done? I'd like to merge this soon and start updates on the loki side referencing it :)

/cc @cyriltovena @slim-bean

2020-10-12 14:05 UTC, torstenwalter commented
@owen-d Whom from Grafana side would need to approve the PR?
Which people should be granted write permissions to this repository? Is it possible to come up with an initial list of people which we could add as maintainers and also add to CODEOWNERS?

2020-10-19 13:53 UTC, unguiculus commented
Note that charts in the Loki charts repo are signed. This needs to be taken car of here as well.

2020-10-19 16:47 UTC, torstenwalter commented
> Note that charts in the Loki charts repo are signed. This needs to be taken care of here as well.

Do you know how to do it with chart releaser GitHub action?

2020-10-20 15:17 UTC, unguiculus commented
I just checked. It currently can't be done with the GitHub action. chart-releaser itself supports signed charts for index and release creation. Meanwhile, chart-releaser also has support for packaging (without signing). But that's not used by the action yet. So, there's a few things left to do. I'll try and look into it.

2020-11-26 18:36 UTC, zanhsieh requested changes

2020-11-26 18:36 UTC, zanhsieh commented on charts/loki/templates/configmap-alert.yaml
> +{{- end }}
maybe extra empty line here.

2020-11-26 18:52 UTC, torstenwalter commented
I needed to do a force push to be able to include latest commits from loki repository. Will try to fix the build issues in the next days.

2020-11-26 19:33 UTC, zanhsieh approved these changes

2020-11-26 20:47 UTC, cyriltovena commented
@scottrigby @torstenwalter @unguiculus 

Thank you for all the hard work and the patience !

2020-11-26 20:49 UTC, cyriltovena commented
We should talk about how to finish this during our next community call on thursday, you're all welcome see https://docs.google.com/document/d/1MNjiHQxwFukm2J4NJRWyRgRIiK7VpokYyATzJ5ce-O8/edit

2020-11-26 22:03 UTC, torstenwalter commented
Should we also copy previous releases to this repo?

2020-11-30 19:42 UTC, torstenwalter commented
> We should talk about how to finish this during our next community call on thursday, you're all welcome see https://docs.google.com/document/d/1MNjiHQxwFukm2J4NJRWyRgRIiK7VpokYyATzJ5ce-O8/edit

I am sorry I can't join this week due to work related stuff.

2020-11-30 20:07 UTC, unguiculus commented
@cyriltovena I'm planning to join.

2020-12-10 00:25 UTC, torstenwalter commented
This is superseded by #112 #113 #114 and #120

2020-12-10 00:25 UTC, closed without merging