add hostPort support for promtail
grafana/helm-charts pull request #431
Opened 2021-05-10 11:28 UTC by lmercl

There is one approach, when you need to support to promtail listen on local host port. It when you need to collect logs from kubernetes nodes and you want to push these logs to local host port, not to k8s service and to be addicted  to kubernetes DNS.
Working rsyslog config is:
`action(type="omfwd" protocol="tcp" port="31514" target="0.0.0.0" Template="RSYSLOG_SyslogProtocol23Format" TCP_Framing="octet-counted")`

2021-05-13 16:35 UTC, unguiculus requested changes
You will have to regenerate the readme using this command:

`docker run --rm --volume "$(pwd):/helm-docs" -u "$(id -u)" jnorwood/helm-docs:v1.4.0`

2021-05-13 16:35 UTC, unguiculus commented on charts/promtail/values.yaml
> +#    #hostPort: 31514
Uncomment the port and make it `null`.
```suggestion
    hostPort: null
```

2022-06-15 18:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=431) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=431) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=431) it.</sub>

2022-09-14 16:30 UTC, zanhsieh commented
@lmercl 
Closed this PR since has been a long time. Feel free to reopen and rebase the PR.

2022-09-14 16:30 UTC, closed without merging