feat: allow for potentially more/different initContainers
grafana/helm-charts pull request #475
Opened 2021-06-07 06:05 UTC by pitwegner

In order for the promtail process to run as non-root, an init container must change the permissions of the `/run/promtail` directory. This is not accounted for in the current version of the chart.

2021-06-11 15:39 UTC, Whyeasy requested changes

2021-06-11 15:39 UTC, Whyeasy commented on charts/promtail/values.yaml
> +initContainers:
I think it would be better to provide an empty list and provide a commented example. By default we don't enable init containers.

2022-06-15 18:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=475) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=475) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=475) it.</sub>

2022-08-05 15:37 UTC, Darnesey commented
Are there any updates on this Pull Request? My company really wants to ensure none of our active containers are running as root.

2022-08-18 22:29 UTC, zanhsieh commented
Close in favour of https://github.com/grafana/helm-charts/pull/1680 .

2022-08-18 22:29 UTC, closed without merging