bump kiwigrid/k8s-sidecar to v1.12.1
grafana/helm-charts pull request #501
Opened 2021-06-16 10:43 UTC by MatthiasWinzeler

Hi folks

`kiwigrid/k8s-sidecar` [was vulnerable to some CVEs](https://github.com/kiwigrid/k8s-sidecar/pull/133) - v1.12.1 fixes them. Could you update the reference?

I tested locally that the grafana dashboard import still works - so should be quite safe to bump it.

2021-06-16 11:04 UTC, zanhsieh commented
@MatthiasWinzeler 
Could you bump the chart version to latest and sign the DCO please? Thank you.

2021-06-16 11:04 UTC, zanhsieh submitted a review, later dismissed

2021-06-16 11:20 UTC, MatthiasWinzeler commented
@zanhsieh sure, will do! I was just told that the fix will actually land with 1.12.2, so I'll wait for that one.

2021-06-16 13:26 UTC, mrueg commented
@MatthiasWinzeler can you also update version value in the README.md table?

2021-06-16 13:35 UTC, MatthiasWinzeler commented
@mrueg yes - done in https://github.com/grafana/helm-charts/pull/501/commits/f2615e423bd36d97c310fe46841aeb6663f28d06

2021-06-16 13:53 UTC, Xtigyro requested changes
@MatthiasWinzeler Could you please bump the minor chart version (not the patch version)? We're updating the minor version of a component with this PR.

2021-06-16 14:01 UTC, MatthiasWinzeler commented
@Xtigyro sure, sounds reasonable. done with https://github.com/grafana/helm-charts/pull/501/commits/141d27731b63ed6245ac892b4ac61c3996bf6ebc

2021-06-16 15:13 UTC, Xtigyro approved these changes
@MatthiasWinzeler Thank you! 🥇

2021-06-16 15:13 UTC, merged

2021-06-17 12:24 UTC, MatthiasWinzeler commented
@Xtigyro you're welcome - thanks for reacting so quickly, it's a pleasure!