added support for Grafana image renderer callback protocol customizat…
grafana/helm-charts pull request #895
Opened 2021-12-14 14:15 UTC by ethernoy

Resolve https://github.com/grafana/helm-charts/issues/889

Signed-off-by: Ethern Su <ehaprime@gmail.com>

2021-12-15 17:48 UTC, zanhsieh commented
@ethernoy 
Could you remove test.yaml? We already have some test under ci.

2021-12-16 02:53 UTC, ethernoy commented
> @ethernoy Could you remove test.yaml? We already have some test under ci. Also please bump the chart version to latest. Thank you.

Thanks for noticing, this file was added by mistake. Removed it.

2021-12-16 07:17 UTC, zanhsieh commented
@ethernoy 
Could you sign DCO ? The instruction should be on Details next to "DCO Action required after 1s — DCO" in this page below.

2021-12-16 14:49 UTC, ethernoy commented
@zanhsieh Done

2021-12-16 15:32 UTC, zanhsieh requested changes

2021-12-16 15:32 UTC, zanhsieh commented on charts/grafana/README.md
> +| `imageRenderer.grafanaProtocol`            | Protocol to use for image renderer callback url                                    | `'http'`                         |
Please align with line 230 `http`

2021-12-16 15:33 UTC, zanhsieh commented
@ethernoy 
Also the Chart version bump is needed. Thank you.

2021-12-17 13:46 UTC, ethernoy commented
> @ethernoy Also the Chart version bump is needed. Thank you.

Both changes implemented.

2021-12-17 16:11 UTC, zanhsieh approved these changes

2021-12-17 16:15 UTC, merged