promtail:  Add config.snippets.extraServerConfigs
grafana/helm-charts pull request #899
Opened 2021-12-15 13:20 UTC by superbrothers

Similar to `extraClientConfigs`, `config.snippets.extraServerConfigs` is added to the config file's 'server' block.

I would like to use this change to add `health_check_target` setting to the config file.

2022-06-15 17:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/helm-charts?pullRequest=899) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=899) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=899) it.</sub>

2022-06-28 22:14 UTC, trevorwhitney requested changes

2022-07-05 19:21 UTC, trevorwhitney commented
@superbrothers looks like we just need a chart version bump to get this merged in. thanks!

2022-07-06 00:58 UTC, superbrothers commented
@trevorwhitney I've done it.

2022-07-08 07:25 UTC, merged