loki: Make /tmp R/W to fix compactor retention
grafana/helm-charts pull request #967
Opened 2022-01-16 15:26 UTC by almson

Fixed #609

2022-01-17 09:16 UTC, zanhsieh commented
@almson 
Please sign DCO. Thank you.

2022-02-15 08:41 UTC, jortkoopmans commented
@zanhsieh and/or @slim-bean ; could this PR get a review please 😊, now that the DCO has been signed? Thanks @almson for your efforts.

2022-02-15 10:12 UTC, zanhsieh approved these changes

2022-02-15 10:13 UTC, zanhsieh requested changes

2022-02-15 10:13 UTC, zanhsieh commented on charts/loki/Chart.yaml
> +version: 2.9.1
now 2.9.2

2022-02-15 13:40 UTC, t106362512 commented on charts/loki/templates/statefulset.yaml
> +        - name: tmp
If .Values.persistence.existingClaim is set, the volume tmp will not be created, so maybe this line can be moved to line 109

2022-02-15 14:21 UTC, t106362512 requested changes
.

2022-02-15 14:22 UTC, t106362512 requested changes
.

2022-02-17 13:13 UTC, almson commented
Bumped version and fixed embarrassing oversight.

2022-02-17 14:33 UTC, zanhsieh approved these changes

2022-02-17 19:07 UTC, torstenwalter approved these changes

2022-02-17 19:07 UTC, merged